// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240609155044_AddDataroute")]
    partial class AddDataroute
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("File");
                });

            modelBuilder.Entity("backend.Models.GraphData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RepId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GraphData");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f2e68c4-13f3-4966-930b-9e7edde381b9"),
                            Latitude = 73.099999999999994,
                            Longitude = 80.0,
                            PointName = "Бухта Север и Диксон",
                            RepId = 1010
                        },
                        new
                        {
                            Id = new Guid("36539d4d-742a-4acd-a463-86b0d045aa84"),
                            Latitude = 69.400000000000006,
                            Longitude = 86.150000000000006,
                            PointName = "Дудинка",
                            RepId = 1007
                        },
                        new
                        {
                            Id = new Guid("2cd7710f-93e8-4403-978b-7fa228b41026"),
                            Latitude = 69.900000000000006,
                            Longitude = 44.600000000000001,
                            PointName = "кромка льда на Западе",
                            RepId = 2002
                        },
                        new
                        {
                            Id = new Guid("ca1c34b8-c4b1-4efc-8eba-95357f27831a"),
                            Latitude = 69.150000000000006,
                            Longitude = 57.68,
                            PointName = "Варандей-Приразломное",
                            RepId = 1015
                        },
                        new
                        {
                            Id = new Guid("01a8fdca-50ec-49b1-8fbe-0e62cbccaa57"),
                            Latitude = 73.0,
                            Longitude = 44.0,
                            PointName = "Штокман",
                            RepId = 1012
                        },
                        new
                        {
                            Id = new Guid("07d60837-cf1d-4a2f-b1e4-158fc246cdfe"),
                            Latitude = 71.5,
                            Longitude = 22.0,
                            PointName = "Окно в Европу",
                            RepId = 2001
                        },
                        new
                        {
                            Id = new Guid("cedec142-f47e-4a62-93e4-a11a9ed6b99b"),
                            Latitude = 74.599999999999994,
                            Longitude = 63.899999999999999,
                            PointName = "Победа месторождение",
                            RepId = 1011
                        },
                        new
                        {
                            Id = new Guid("3a437f7c-9748-4d5e-b401-0c6cc7d26344"),
                            Latitude = 76.400000000000006,
                            Longitude = 86.400000000000006,
                            PointName = "Карское - 3 (центр)",
                            RepId = 2008
                        },
                        new
                        {
                            Id = new Guid("f25e5db7-b2ed-48f4-9531-1118d4b90730"),
                            Latitude = 77.599999999999994,
                            Longitude = 107.7,
                            PointName = "пролив Вилькицкого - 3",
                            RepId = 2013
                        },
                        new
                        {
                            Id = new Guid("a8623293-348f-4a15-847a-dbb16d35ec02"),
                            Latitude = 74.900000000000006,
                            Longitude = 116.7,
                            PointName = "Лаптевых - 4 (юг)",
                            RepId = 2018
                        },
                        new
                        {
                            Id = new Guid("fdbf016c-aef3-46a5-99a2-26eb24ed7708"),
                            Latitude = 73.099999999999994,
                            Longitude = 72.700000000000003,
                            PointName = "Вход в Обскую губу",
                            RepId = 2009
                        },
                        new
                        {
                            Id = new Guid("de8e81d2-7cb3-427f-b1e7-a5b8d080b424"),
                            Latitude = 68.5,
                            Longitude = 73.700000000000003,
                            PointName = "Новый порт",
                            RepId = 1004
                        },
                        new
                        {
                            Id = new Guid("5f3dc2ce-30a0-4630-811e-ced9a3fbc986"),
                            Latitude = 76.75,
                            Longitude = 116.0,
                            PointName = "Лаптевых - 1 (центр)",
                            RepId = 2015
                        },
                        new
                        {
                            Id = new Guid("527c274c-0ae9-4175-a118-e86cd8e61f92"),
                            Latitude = 74.0,
                            Longitude = 76.700000000000003,
                            PointName = "Карское - 1 (сбор каравана)",
                            RepId = 2006
                        },
                        new
                        {
                            Id = new Guid("8bf3f460-b5bb-42fb-b287-73da7417b0c5"),
                            Latitude = 72.349999999999994,
                            Longitude = 79.599999999999994,
                            PointName = "Лескинское м-е",
                            RepId = 1014
                        },
                        new
                        {
                            Id = new Guid("5bd368ce-1ddd-4d11-ada8-57c3d81ca1cc"),
                            Latitude = 70.299999999999997,
                            Longitude = 57.799999999999997,
                            PointName = "Карские ворота",
                            RepId = 2005
                        },
                        new
                        {
                            Id = new Guid("4d43a22a-4002-4852-ad79-0ac4cd157e90"),
                            Latitude = 77.299999999999997,
                            Longitude = 67.700000000000003,
                            PointName = "Мыс Желания",
                            RepId = 2003
                        },
                        new
                        {
                            Id = new Guid("38d1879b-1953-4981-b663-78552fbc9dcf"),
                            Latitude = 71.739999999999995,
                            Longitude = 184.69999999999999,
                            PointName = "остров Врангеля",
                            RepId = 2026
                        },
                        new
                        {
                            Id = new Guid("8dd71762-fb79-4f2a-8b49-11299b326ab9"),
                            Latitude = 70.700000000000003,
                            Longitude = 170.5,
                            PointName = "Восточно-Сибирское - 1 (восток)",
                            RepId = 2023
                        },
                        new
                        {
                            Id = new Guid("2d44b099-d686-4be1-8bb7-a322d3eaedb8"),
                            Latitude = 77.799999999999997,
                            Longitude = 104.09999999999999,
                            PointName = "пролив Вилькицкого - восток",
                            RepId = 2012
                        },
                        new
                        {
                            Id = new Guid("524ebee7-f8b3-40a9-bdfd-af1de8467cec"),
                            Latitude = 77.700000000000003,
                            Longitude = 99.5,
                            PointName = "пролив Вилькицкого - запад",
                            RepId = 2011
                        },
                        new
                        {
                            Id = new Guid("a41366a3-45a8-4aec-9a49-856dcc43f3d0"),
                            Latitude = 76.200000000000003,
                            Longitude = 58.299999999999997,
                            PointName = "около Новой Земли",
                            RepId = 2004
                        },
                        new
                        {
                            Id = new Guid("37141ea6-4c87-43fb-999a-47ce08af3c67"),
                            Latitude = 74.400000000000006,
                            Longitude = 139.0,
                            PointName = "Пролив Санникова - 1",
                            RepId = 2020
                        },
                        new
                        {
                            Id = new Guid("328ebc77-d1f0-464e-bb17-43808f16c19e"),
                            Latitude = 74.299999999999997,
                            Longitude = 146.69999999999999,
                            PointName = "Пролив Санникова - 2",
                            RepId = 2021
                        },
                        new
                        {
                            Id = new Guid("e3e10f44-bf14-4e0e-a81a-4fbe5b02e2fe"),
                            Latitude = 74.0,
                            Longitude = 128.09999999999999,
                            PointName = "устье Лены",
                            RepId = 2019
                        },
                        new
                        {
                            Id = new Guid("6af85eae-4f11-4f41-b91f-bcb80404f9b8"),
                            Latitude = 71.299999999999997,
                            Longitude = 72.150000000000006,
                            PointName = "Сабетта",
                            RepId = 1003
                        },
                        new
                        {
                            Id = new Guid("7351da5c-89ce-43c8-8e97-b53a4509f6e8"),
                            Latitude = 69.099999999999994,
                            Longitude = 169.40000000000001,
                            PointName = "мыс.Наглёйнын",
                            RepId = 1009
                        },
                        new
                        {
                            Id = new Guid("ceeb1cf4-5ad0-4678-a487-936f84d28fd9"),
                            Latitude = 69.900000000000006,
                            Longitude = 179.0,
                            PointName = "пролив Лонга",
                            RepId = 2027
                        },
                        new
                        {
                            Id = new Guid("ad4eac9d-acc5-497a-aa02-e24530aaca6e"),
                            Latitude = 73.5,
                            Longitude = 169.90000000000001,
                            PointName = "Восточно-Сибирское - 3 (север)",
                            RepId = 2025
                        },
                        new
                        {
                            Id = new Guid("c8e28b13-d916-4241-b1b2-da9ba7ff7525"),
                            Latitude = 64.950000000000003,
                            Longitude = 40.049999999999997,
                            PointName = "Архангельск",
                            RepId = 1002
                        },
                        new
                        {
                            Id = new Guid("e6a2f4a1-8dc3-4217-a54d-bdbc340ab265"),
                            Latitude = 75.900000000000006,
                            Longitude = 152.59999999999999,
                            PointName = "Лаптевых - 3 (восток)",
                            RepId = 2017
                        },
                        new
                        {
                            Id = new Guid("886fd0dd-7c82-4a52-8d45-71b2fdac052d"),
                            Latitude = 68.370000000000005,
                            Longitude = 54.600000000000001,
                            PointName = "МОТ Печора",
                            RepId = 1017
                        },
                        new
                        {
                            Id = new Guid("61b66f53-436a-47bc-9603-b34550637007"),
                            Latitude = 73.700000000000003,
                            Longitude = 109.26000000000001,
                            PointName = "Хатангский залив",
                            RepId = 1008
                        },
                        new
                        {
                            Id = new Guid("736151b9-8b59-4aab-aebe-087cfd3ada39"),
                            Latitude = 72.0,
                            Longitude = 159.5,
                            PointName = "Восточно-Сибирское - 2 (запад)",
                            RepId = 2024
                        },
                        new
                        {
                            Id = new Guid("d0ad34ea-11cc-4d04-80b2-c49b4c1bfc65"),
                            Latitude = 72.400000000000006,
                            Longitude = 65.599999999999994,
                            PointName = "Ленинградское-Русановское",
                            RepId = 1013
                        },
                        new
                        {
                            Id = new Guid("41fb741f-5157-45ba-8b3b-c19bf3d74a91"),
                            Latitude = 71.0,
                            Longitude = 73.730000000000004,
                            PointName = "терминал Утренний",
                            RepId = 1005
                        },
                        new
                        {
                            Id = new Guid("043514f3-2126-496d-9763-3edd794f713c"),
                            Latitude = 76.5,
                            Longitude = 97.599999999999994,
                            PointName = "Таймырский залив",
                            RepId = 2010
                        },
                        new
                        {
                            Id = new Guid("c1dd41b6-a598-4b2c-8c6a-be6ca552d67f"),
                            Latitude = 64.200000000000003,
                            Longitude = 188.19999999999999,
                            PointName = "Берингово",
                            RepId = 2029
                        },
                        new
                        {
                            Id = new Guid("5d26f2d1-229f-4825-a92d-05f4790810a5"),
                            Latitude = 60.700000000000003,
                            Longitude = 175.30000000000001,
                            PointName = "кромка льда на Востоке",
                            RepId = 2030
                        },
                        new
                        {
                            Id = new Guid("cbf227d3-aaf6-4382-878e-ca082edbabd2"),
                            Latitude = 69.75,
                            Longitude = 169.90000000000001,
                            PointName = "Рейд Певек",
                            RepId = 1006
                        },
                        new
                        {
                            Id = new Guid("1b9dd7bd-ea85-4571-aa42-865cc6642b40"),
                            Latitude = 75.5,
                            Longitude = 131.5,
                            PointName = "Лаптевых - 2 (центр)",
                            RepId = 2016
                        },
                        new
                        {
                            Id = new Guid("5a48f3cb-4f82-4e75-888f-b033537f06f5"),
                            Latitude = 69.5,
                            Longitude = 33.75,
                            PointName = "Рейд Мурманска",
                            RepId = 1001
                        },
                        new
                        {
                            Id = new Guid("a2b6fe3d-16d6-4a96-b3a1-429bc7215bfd"),
                            Latitude = 76.700000000000003,
                            Longitude = 140.80000000000001,
                            PointName = "остров Котельный",
                            RepId = 2022
                        },
                        new
                        {
                            Id = new Guid("5d30983d-ad2d-4ecd-afe6-5eab1cdc626b"),
                            Latitude = 74.799999999999997,
                            Longitude = 84.200000000000003,
                            PointName = "Карское - 2 (прибрежный)",
                            RepId = 2007
                        },
                        new
                        {
                            Id = new Guid("6810dbd5-e1e5-4ada-a949-7bf8620973a7"),
                            Latitude = 67.579999999999998,
                            Longitude = 47.82,
                            PointName = "Индига",
                            RepId = 1016
                        },
                        new
                        {
                            Id = new Guid("981f6d6a-91d1-44bf-9139-bbe42c8fa591"),
                            Latitude = 65.900000000000006,
                            Longitude = -169.34999999999999,
                            PointName = "Берингов пролив",
                            RepId = 2028
                        },
                        new
                        {
                            Id = new Guid("1d28a1f8-3b15-48eb-836f-317d1fcb95f0"),
                            Latitude = 55.700000000000003,
                            Longitude = 164.25,
                            PointName = "Окно в Азию",
                            RepId = 2031
                        });
                });

            modelBuilder.Entity("backend.Models.IntegerIceClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("MinSpeed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("IntegerIceClass");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d314cec1-2e9d-47dd-9d64-ae99d70ae7b2"),
                            MaxSpeed = 21,
                            MinSpeed = 20
                        },
                        new
                        {
                            Id = new Guid("355e04f7-319a-47d3-87ed-81d28efb7e24"),
                            MaxSpeed = 19,
                            MinSpeed = 15
                        },
                        new
                        {
                            Id = new Guid("bb8a4d9b-b972-4099-a5e2-91332674fe12"),
                            MaxSpeed = 14,
                            MinSpeed = 10
                        });
                });

            modelBuilder.Entity("backend.Models.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FinishId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Length")
                        .HasColumnType("double precision");

                    b.Property<Guid>("StartId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StatusRoute")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FinishId");

                    b.HasIndex("StartId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a320690-9968-4087-a1bc-f84507a9da07"),
                            FinishId = new Guid("5bd368ce-1ddd-4d11-ada8-57c3d81ca1cc"),
                            Length = 270.01664160000001,
                            StartId = new Guid("6810dbd5-e1e5-4ada-a949-7bf8620973a7"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("a686c277-50e9-448f-a3b7-d54c58c7e8cf"),
                            FinishId = new Guid("de8e81d2-7cb3-427f-b1e7-a5b8d080b424"),
                            Length = 277.18983630000002,
                            StartId = new Guid("fdbf016c-aef3-46a5-99a2-26eb24ed7708"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("3f99122d-86bc-458d-aab8-9aca626eb88f"),
                            FinishId = new Guid("cbf227d3-aaf6-4382-878e-ca082edbabd2"),
                            Length = 58.390351320000001,
                            StartId = new Guid("8dd71762-fb79-4f2a-8b49-11299b326ab9"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("f5b0093e-d1e7-430b-95b1-e68d2f2335a5"),
                            FinishId = new Guid("4d43a22a-4002-4852-ad79-0ac4cd157e90"),
                            Length = 238.85898850000001,
                            StartId = new Guid("527c274c-0ae9-4175-a118-e86cd8e61f92"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("0b467e19-47eb-4cde-a560-eac16a178029"),
                            FinishId = new Guid("527c274c-0ae9-4175-a118-e86cd8e61f92"),
                            Length = 86.930049159999996,
                            StartId = new Guid("fdbf016c-aef3-46a5-99a2-26eb24ed7708"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("d0c22877-f2bd-4c24-9bb3-c0dd4090b02d"),
                            FinishId = new Guid("07d60837-cf1d-4a2f-b1e4-158fc246cdfe"),
                            Length = 655.35573739999995,
                            StartId = new Guid("a41366a3-45a8-4aec-9a49-856dcc43f3d0"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("81f64872-d565-4efa-8acc-67024587d998"),
                            FinishId = new Guid("07d60837-cf1d-4a2f-b1e4-158fc246cdfe"),
                            Length = 410.57011160000002,
                            StartId = new Guid("01a8fdca-50ec-49b1-8fbe-0e62cbccaa57"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("5ce76256-23c4-460e-8243-daaffb8fb5ac"),
                            FinishId = new Guid("c1dd41b6-a598-4b2c-8c6a-be6ca552d67f"),
                            Length = 119.56344919999999,
                            StartId = new Guid("981f6d6a-91d1-44bf-9139-bbe42c8fa591"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("a834f71a-d427-4468-8389-090b0665b9c7"),
                            FinishId = new Guid("3a437f7c-9748-4d5e-b401-0c6cc7d26344"),
                            Length = 206.8821279,
                            StartId = new Guid("527c274c-0ae9-4175-a118-e86cd8e61f92"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("612a8708-fd0f-4bd0-bec5-79ba341dc867"),
                            FinishId = new Guid("e3e10f44-bf14-4e0e-a81a-4fbe5b02e2fe"),
                            Length = 191.1526107,
                            StartId = new Guid("a8623293-348f-4a15-847a-dbb16d35ec02"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("307b8344-d476-4b2d-a6f5-0a4db568aef9"),
                            FinishId = new Guid("8dd71762-fb79-4f2a-8b49-11299b326ab9"),
                            Length = 178.64541199999999,
                            StartId = new Guid("ceeb1cf4-5ad0-4678-a487-936f84d28fd9"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("1ad2a702-6d01-4bd2-9d37-2b7a0de0fd95"),
                            FinishId = new Guid("736151b9-8b59-4aab-aebe-087cfd3ada39"),
                            Length = 205.7748943,
                            StartId = new Guid("ad4eac9d-acc5-497a-aa02-e24530aaca6e"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("ec6c35ea-1494-469f-92d6-ee7cb8923815"),
                            FinishId = new Guid("37141ea6-4c87-43fb-999a-47ce08af3c67"),
                            Length = 134.30498470000001,
                            StartId = new Guid("1b9dd7bd-ea85-4571-aa42-865cc6642b40"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("dc4ec535-4b72-4304-b985-f9755bb59358"),
                            FinishId = new Guid("e6a2f4a1-8dc3-4217-a54d-bdbc340ab265"),
                            Length = 174.3916815,
                            StartId = new Guid("a2b6fe3d-16d6-4a96-b3a1-429bc7215bfd"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("b0305fe6-67fb-4f67-8300-544a6cf6ea38"),
                            FinishId = new Guid("ca1c34b8-c4b1-4efc-8eba-95357f27831a"),
                            Length = 81.815960799999999,
                            StartId = new Guid("886fd0dd-7c82-4a52-8d45-71b2fdac052d"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("03e000c5-c94c-47ac-a603-20f18c790a48"),
                            FinishId = new Guid("5d30983d-ad2d-4ecd-afe6-5eab1cdc626b"),
                            Length = 123.6831421,
                            StartId = new Guid("5f2e68c4-13f3-4966-930b-9e7edde381b9"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("ebd23baf-fbf6-4df1-a445-dd122f828967"),
                            FinishId = new Guid("e3e10f44-bf14-4e0e-a81a-4fbe5b02e2fe"),
                            Length = 246.24586489999999,
                            StartId = new Guid("5f3dc2ce-30a0-4630-811e-ced9a3fbc986"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("f9928498-0e86-49c0-b36a-b754a1704550"),
                            FinishId = new Guid("a2b6fe3d-16d6-4a96-b3a1-429bc7215bfd"),
                            Length = 339.77822600000002,
                            StartId = new Guid("5f3dc2ce-30a0-4630-811e-ced9a3fbc986"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("280925f8-85a9-431c-8fad-5ea8409210be"),
                            FinishId = new Guid("2cd7710f-93e8-4403-978b-7fa228b41026"),
                            Length = 270.59211690000001,
                            StartId = new Guid("5bd368ce-1ddd-4d11-ada8-57c3d81ca1cc"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("cd9f93a0-4aba-44e4-832b-ccdcb1bd1d1e"),
                            FinishId = new Guid("41fb741f-5157-45ba-8b3b-c19bf3d74a91"),
                            Length = 127.65462359999999,
                            StartId = new Guid("fdbf016c-aef3-46a5-99a2-26eb24ed7708"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("b88890e9-7325-4f89-bf16-eb2e7ad97692"),
                            FinishId = new Guid("61b66f53-436a-47bc-9603-b34550637007"),
                            Length = 140.73600680000001,
                            StartId = new Guid("a8623293-348f-4a15-847a-dbb16d35ec02"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("9012d7cb-de21-4ebb-9c36-d2b3c240d942"),
                            FinishId = new Guid("ca1c34b8-c4b1-4efc-8eba-95357f27831a"),
                            Length = 278.1227556,
                            StartId = new Guid("2cd7710f-93e8-4403-978b-7fa228b41026"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("4d805687-50ca-44e4-8cea-75c9df221eb5"),
                            FinishId = new Guid("36539d4d-742a-4acd-a463-86b0d045aa84"),
                            Length = 251.86265969999999,
                            StartId = new Guid("5f2e68c4-13f3-4966-930b-9e7edde381b9"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("f8b496bc-2a3e-491e-9fdb-b2981a68e3fa"),
                            FinishId = new Guid("8dd71762-fb79-4f2a-8b49-11299b326ab9"),
                            Length = 225.02389769999999,
                            StartId = new Guid("736151b9-8b59-4aab-aebe-087cfd3ada39"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("1bb34daf-2e35-4bd2-a765-8509e9fa6ce2"),
                            FinishId = new Guid("a2b6fe3d-16d6-4a96-b3a1-429bc7215bfd"),
                            Length = 152.20194660000001,
                            StartId = new Guid("1b9dd7bd-ea85-4571-aa42-865cc6642b40"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("25b3bd47-1def-4832-b991-edf6347d9a2f"),
                            FinishId = new Guid("5a48f3cb-4f82-4e75-888f-b033537f06f5"),
                            Length = 288.19191749999999,
                            StartId = new Guid("01a8fdca-50ec-49b1-8fbe-0e62cbccaa57"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("49bb3b9e-20f0-4f01-a067-cca5671d8b5f"),
                            FinishId = new Guid("5f3dc2ce-30a0-4630-811e-ced9a3fbc986"),
                            Length = 121.8205679,
                            StartId = new Guid("f25e5db7-b2ed-48f4-9531-1118d4b90730"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("7ffceca6-d032-4bac-a6e8-1e06b6fa2a8c"),
                            FinishId = new Guid("c8e28b13-d916-4241-b1b2-da9ba7ff7525"),
                            Length = 315.30476279999999,
                            StartId = new Guid("2cd7710f-93e8-4403-978b-7fa228b41026"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("49b5317b-be4b-4c43-af34-85df2f804f20"),
                            FinishId = new Guid("ca1c34b8-c4b1-4efc-8eba-95357f27831a"),
                            Length = 69.168612730000007,
                            StartId = new Guid("5bd368ce-1ddd-4d11-ada8-57c3d81ca1cc"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("746101ed-9ac7-4feb-a61c-e98b1583a717"),
                            FinishId = new Guid("1b9dd7bd-ea85-4571-aa42-865cc6642b40"),
                            Length = 234.89411480000001,
                            StartId = new Guid("5f3dc2ce-30a0-4630-811e-ced9a3fbc986"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("84d02ffa-0efe-4d2b-b29f-5a1a8cab66b6"),
                            FinishId = new Guid("f25e5db7-b2ed-48f4-9531-1118d4b90730"),
                            Length = 47.63018916,
                            StartId = new Guid("2d44b099-d686-4be1-8bb7-a322d3eaedb8"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("cca8676b-85f8-44d9-b47a-b044a852aae8"),
                            FinishId = new Guid("e6a2f4a1-8dc3-4217-a54d-bdbc340ab265"),
                            Length = 308.41519959999999,
                            StartId = new Guid("ad4eac9d-acc5-497a-aa02-e24530aaca6e"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("34f5d4ed-b04f-4167-be17-84504e49681f"),
                            FinishId = new Guid("5f2e68c4-13f3-4966-930b-9e7edde381b9"),
                            Length = 77.963962300000006,
                            StartId = new Guid("527c274c-0ae9-4175-a118-e86cd8e61f92"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("402852ff-85d7-4ace-9361-0c564899a9cc"),
                            FinishId = new Guid("2cd7710f-93e8-4403-978b-7fa228b41026"),
                            Length = 445.92813819999998,
                            StartId = new Guid("a41366a3-45a8-4aec-9a49-856dcc43f3d0"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("65458d95-beff-47c3-b81b-3ea896e55cc9"),
                            FinishId = new Guid("8dd71762-fb79-4f2a-8b49-11299b326ab9"),
                            Length = 436.27169129999999,
                            StartId = new Guid("e6a2f4a1-8dc3-4217-a54d-bdbc340ab265"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("aa5cca2e-b9c4-4ca3-a27e-598c8109f6d1"),
                            FinishId = new Guid("a8623293-348f-4a15-847a-dbb16d35ec02"),
                            Length = 229.4577372,
                            StartId = new Guid("1b9dd7bd-ea85-4571-aa42-865cc6642b40"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("7bd2ddb6-708d-4995-8c5b-e6ffc2c3721a"),
                            FinishId = new Guid("01a8fdca-50ec-49b1-8fbe-0e62cbccaa57"),
                            Length = 297.15080849999998,
                            StartId = new Guid("a41366a3-45a8-4aec-9a49-856dcc43f3d0"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("5330c9e8-ad59-46e1-a9f3-a2bb7c1099fe"),
                            FinishId = new Guid("d0ad34ea-11cc-4d04-80b2-c49b4c1bfc65"),
                            Length = 296.3206745,
                            StartId = new Guid("4d43a22a-4002-4852-ad79-0ac4cd157e90"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("182c3c4c-68c6-43b4-a0c8-937b0c79f03d"),
                            FinishId = new Guid("38d1879b-1953-4981-b663-78552fbc9dcf"),
                            Length = 373.63082739999999,
                            StartId = new Guid("981f6d6a-91d1-44bf-9139-bbe42c8fa591"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("16ff2d7b-4518-4c92-83fd-4950cf8d0448"),
                            FinishId = new Guid("8dd71762-fb79-4f2a-8b49-11299b326ab9"),
                            Length = 281.08704540000002,
                            StartId = new Guid("38d1879b-1953-4981-b663-78552fbc9dcf"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("ee09052a-c454-4158-95e9-1207f6b6bb55"),
                            FinishId = new Guid("7351da5c-89ce-43c8-8e97-b53a4509f6e8"),
                            Length = 98.815529369999993,
                            StartId = new Guid("8dd71762-fb79-4f2a-8b49-11299b326ab9"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("562269ca-a6dd-4f73-a631-b281f60cd8db"),
                            FinishId = new Guid("1d28a1f8-3b15-48eb-836f-317d1fcb95f0"),
                            Length = 460.28483269999998,
                            StartId = new Guid("5d26f2d1-229f-4825-a92d-05f4790810a5"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("8ef102b3-bb75-4205-b5e6-9cca5b17fa8f"),
                            FinishId = new Guid("736151b9-8b59-4aab-aebe-087cfd3ada39"),
                            Length = 260.57011360000001,
                            StartId = new Guid("e6a2f4a1-8dc3-4217-a54d-bdbc340ab265"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("f381ef32-06f7-4a94-9de1-53fdbde4405b"),
                            FinishId = new Guid("37141ea6-4c87-43fb-999a-47ce08af3c67"),
                            Length = 179.7422785,
                            StartId = new Guid("e3e10f44-bf14-4e0e-a81a-4fbe5b02e2fe"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("ca94d2c4-a9e6-426f-8154-b125f8178aba"),
                            FinishId = new Guid("4d43a22a-4002-4852-ad79-0ac4cd157e90"),
                            Length = 263.63934649999999,
                            StartId = new Guid("fdbf016c-aef3-46a5-99a2-26eb24ed7708"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("55a1892a-d4e7-4a96-9920-a274417bf162"),
                            FinishId = new Guid("981f6d6a-91d1-44bf-9139-bbe42c8fa591"),
                            Length = 355.62316140000001,
                            StartId = new Guid("ceeb1cf4-5ad0-4678-a487-936f84d28fd9"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("b2cc7142-a2d1-4e8c-ac22-8d6d8a01b597"),
                            FinishId = new Guid("043514f3-2126-496d-9763-3edd794f713c"),
                            Length = 157.6035239,
                            StartId = new Guid("3a437f7c-9748-4d5e-b401-0c6cc7d26344"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("d2d2798f-a126-45ff-9bda-9a24ea78a035"),
                            FinishId = new Guid("524ebee7-f8b3-40a9-bdfd-af1de8467cec"),
                            Length = 192.45222290000001,
                            StartId = new Guid("3a437f7c-9748-4d5e-b401-0c6cc7d26344"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("3796da3c-47b6-4f01-be67-c24969a58783"),
                            FinishId = new Guid("527c274c-0ae9-4175-a118-e86cd8e61f92"),
                            Length = 215.05323759999999,
                            StartId = new Guid("d0ad34ea-11cc-4d04-80b2-c49b4c1bfc65"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("27915e61-df88-44c3-b298-7c20149b854b"),
                            FinishId = new Guid("043514f3-2126-496d-9763-3edd794f713c"),
                            Length = 223.5714878,
                            StartId = new Guid("5d30983d-ad2d-4ecd-afe6-5eab1cdc626b"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("7afa6639-8e8f-4443-8555-d749d1635665"),
                            FinishId = new Guid("3a437f7c-9748-4d5e-b401-0c6cc7d26344"),
                            Length = 352.93682100000001,
                            StartId = new Guid("cedec142-f47e-4a62-93e4-a11a9ed6b99b"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("a0270742-1b6c-4a5a-89f0-372955d59683"),
                            FinishId = new Guid("6af85eae-4f11-4f41-b91f-bcb80404f9b8"),
                            Length = 108.6630553,
                            StartId = new Guid("fdbf016c-aef3-46a5-99a2-26eb24ed7708"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("5287fa1e-ecab-47b7-919c-d336a4a1b300"),
                            FinishId = new Guid("5d26f2d1-229f-4825-a92d-05f4790810a5"),
                            Length = 414.6912251,
                            StartId = new Guid("c1dd41b6-a598-4b2c-8c6a-be6ca552d67f"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("bf2534d4-ba0f-4aa5-9e7e-f7a535a519dc"),
                            FinishId = new Guid("5bd368ce-1ddd-4d11-ada8-57c3d81ca1cc"),
                            Length = 410.45491850000002,
                            StartId = new Guid("527c274c-0ae9-4175-a118-e86cd8e61f92"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("6d1391ef-662e-4a9b-a4e4-c85944f8dc2d"),
                            FinishId = new Guid("4d43a22a-4002-4852-ad79-0ac4cd157e90"),
                            Length = 260.1771091,
                            StartId = new Guid("3a437f7c-9748-4d5e-b401-0c6cc7d26344"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("8f3bb296-88d8-4660-b880-6768bae90cbe"),
                            FinishId = new Guid("4d43a22a-4002-4852-ad79-0ac4cd157e90"),
                            Length = 171.4172136,
                            StartId = new Guid("cedec142-f47e-4a62-93e4-a11a9ed6b99b"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("8951bd4e-09c3-48c5-b2fb-e5ad88855f55"),
                            FinishId = new Guid("2d44b099-d686-4be1-8bb7-a322d3eaedb8"),
                            Length = 116.7439955,
                            StartId = new Guid("043514f3-2126-496d-9763-3edd794f713c"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("b4360c57-3ec0-4a79-9937-a911f09cc32e"),
                            FinishId = new Guid("328ebc77-d1f0-464e-bb17-43808f16c19e"),
                            Length = 261.60058900000001,
                            StartId = new Guid("736151b9-8b59-4aab-aebe-087cfd3ada39"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("eb1907a8-7a16-4603-a77b-8b0f73f87709"),
                            FinishId = new Guid("4d43a22a-4002-4852-ad79-0ac4cd157e90"),
                            Length = 409.31115749999998,
                            StartId = new Guid("524ebee7-f8b3-40a9-bdfd-af1de8467cec"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("942545d3-a92c-43aa-9075-744803379fdc"),
                            FinishId = new Guid("5bd368ce-1ddd-4d11-ada8-57c3d81ca1cc"),
                            Length = 326.43284169999998,
                            StartId = new Guid("fdbf016c-aef3-46a5-99a2-26eb24ed7708"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("ca9e3c09-6358-405e-aa29-ff21836ce220"),
                            FinishId = new Guid("5bd368ce-1ddd-4d11-ada8-57c3d81ca1cc"),
                            Length = 195.73284430000001,
                            StartId = new Guid("d0ad34ea-11cc-4d04-80b2-c49b4c1bfc65"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("d4321543-da3a-44f7-94de-188d237b94f6"),
                            FinishId = new Guid("2cd7710f-93e8-4403-978b-7fa228b41026"),
                            Length = 156.0644819,
                            StartId = new Guid("6810dbd5-e1e5-4ada-a949-7bf8620973a7"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("bffa059a-eecb-4320-8d08-6b370d215a33"),
                            FinishId = new Guid("5f2e68c4-13f3-4966-930b-9e7edde381b9"),
                            Length = 45.642155700000004,
                            StartId = new Guid("8bf3f460-b5bb-42fb-b287-73da7417b0c5"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("dfef185b-5078-4ed1-8e93-0857c13a6990"),
                            FinishId = new Guid("a8623293-348f-4a15-847a-dbb16d35ec02"),
                            Length = 206.59791390000001,
                            StartId = new Guid("f25e5db7-b2ed-48f4-9531-1118d4b90730"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("474661a6-e1be-4a9a-90c8-4489dcb212e9"),
                            FinishId = new Guid("07d60837-cf1d-4a2f-b1e4-158fc246cdfe"),
                            Length = 456.26762389999999,
                            StartId = new Guid("2cd7710f-93e8-4403-978b-7fa228b41026"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("0687b947-ef2c-43a6-bb5c-29b2e8d01aef"),
                            FinishId = new Guid("a41366a3-45a8-4aec-9a49-856dcc43f3d0"),
                            Length = 145.18263640000001,
                            StartId = new Guid("4d43a22a-4002-4852-ad79-0ac4cd157e90"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("4375d104-7852-4441-a93b-40a9df04b3bc"),
                            FinishId = new Guid("ad4eac9d-acc5-497a-aa02-e24530aaca6e"),
                            Length = 275.66045489999999,
                            StartId = new Guid("ceeb1cf4-5ad0-4678-a487-936f84d28fd9"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("69d9b3f8-421e-47a6-a1d8-c3725790ef80"),
                            FinishId = new Guid("5d30983d-ad2d-4ecd-afe6-5eab1cdc626b"),
                            Length = 130.30811159999999,
                            StartId = new Guid("527c274c-0ae9-4175-a118-e86cd8e61f92"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("a3ad7f33-0175-456d-8f03-d699ee577acf"),
                            FinishId = new Guid("524ebee7-f8b3-40a9-bdfd-af1de8467cec"),
                            Length = 58.957502009999999,
                            StartId = new Guid("2d44b099-d686-4be1-8bb7-a322d3eaedb8"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("20020a97-2b39-48d8-a1e8-c09e634fd580"),
                            FinishId = new Guid("5bd368ce-1ddd-4d11-ada8-57c3d81ca1cc"),
                            Length = 280.78065989999999,
                            StartId = new Guid("cedec142-f47e-4a62-93e4-a11a9ed6b99b"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("77181861-fd3f-4cc8-a24a-bc47415e113b"),
                            FinishId = new Guid("5a48f3cb-4f82-4e75-888f-b033537f06f5"),
                            Length = 227.22693039999999,
                            StartId = new Guid("2cd7710f-93e8-4403-978b-7fa228b41026"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("d266ab62-fa59-47c4-96ba-e30df5f274cf"),
                            FinishId = new Guid("328ebc77-d1f0-464e-bb17-43808f16c19e"),
                            Length = 124.90922089999999,
                            StartId = new Guid("37141ea6-4c87-43fb-999a-47ce08af3c67"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("6f598a93-217f-448c-8c79-e1e69b3d7109"),
                            FinishId = new Guid("ad4eac9d-acc5-497a-aa02-e24530aaca6e"),
                            Length = 285.07951350000002,
                            StartId = new Guid("38d1879b-1953-4981-b663-78552fbc9dcf"),
                            StatusRoute = 2
                        });
                });

            modelBuilder.Entity("backend.Models.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ShipClassId");

                    b.ToTable("Ship");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d88bbd0c-37e8-4071-b322-f929b94ed5a9"),
                            ShipClassId = new Guid("c0ad8b7d-49d0-4cbe-ab0f-619da96169ef"),
                            ShipName = "ДЮК II",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("5b6c217e-3924-4f85-a807-9b6350380455"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "САРМАТ",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("7c21a2bd-b648-40f8-abc4-11324c44759a"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "EDUARD TOLL",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("1e622781-9e4c-43aa-8829-712460b670a1"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "GEORGIY USHAKOV",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("86e5ac50-9bc4-48d9-b2be-a1164b989564"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "RUDOLF SAMOYLOVICH",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("10b6f0d7-3840-4855-8f39-0a61625aa26e"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "VLADIMIR VORONIN",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("ddd4093e-bde5-4cec-abcb-30106756db19"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "NIKOLAY YEVGENOV",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("2657c5cb-8e58-414b-bb1c-7219a4e53be1"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "CHRISTOPHE DE MARGERIE",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("478d7bd3-8083-4ddc-86ec-302fd2241d19"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "BORIS VILKITSKY",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = new Guid("2a05c6e2-b063-489e-8ec6-afc18f628e0f"),
                            ShipClassId = new Guid("c0ad8b7d-49d0-4cbe-ab0f-619da96169ef"),
                            ShipName = "АРКТИКА-2",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = new Guid("9c29708d-99c7-44ea-bd47-d7e93e5c490c"),
                            ShipClassId = new Guid("c0ad8b7d-49d0-4cbe-ab0f-619da96169ef"),
                            ShipName = "ИНЖЕНЕР ВЕШНЯКОВ",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = new Guid("83b9eca0-9965-4728-b5e9-c4374bdf494c"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "ТАМБЕЙ",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = new Guid("4d900647-a7a7-40d9-bb7d-0c6ee5521306"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "ШТУРМАН АЛЬБАНОВ",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = new Guid("3bd3a2f1-a018-4edc-8740-07ca9a54febf"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "НИКИФОР БЕГИЧЕВ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("29a14431-cb5f-43df-8621-c1d67ced6ae7"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "НОРИЛЬСКИЙ НИКЕЛЬ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("9bce7af3-a85d-4eca-bd21-e76e978d801f"),
                            ShipClassId = new Guid("c0ad8b7d-49d0-4cbe-ab0f-619da96169ef"),
                            ShipName = "АЙС ИГЛ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("99b39674-28a1-4385-958b-cb551e452cc5"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "ШТУРМАН КОШЕЛЕВ",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("7df2830c-88ee-49cc-b98c-0a429ab6be24"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "ШТУРМАН ЩЕРБИНИН",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("0467acc6-4907-4e6d-bb04-f42a27bef7fc"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "ШТУРМАН СКУРАТОВ",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("285e5904-f8f1-4646-93cb-d83b595d6836"),
                            ShipClassId = new Guid("c0ad8b7d-49d0-4cbe-ab0f-619da96169ef"),
                            ShipName = "ИОГАНН МАХМАСТАЛЬ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("ba83e2da-ae8e-4766-9308-a07d731ad23c"),
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipName = "BORIS SOKOLOV",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("e953d6d8-b73a-40a6-b3ea-0623f41e4a4a"),
                            ShipClassId = new Guid("c0ad8b7d-49d0-4cbe-ab0f-619da96169ef"),
                            ShipName = "ИНЖЕНЕР ТРУБИН",
                            Speed = 12.0
                        },
                        new
                        {
                            Id = new Guid("cfd7b8dd-2759-4bb3-a607-7e7884983062"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "БАРЕНЦ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("f5844a2b-126b-4f12-baa5-0da5336ab249"),
                            ShipClassId = new Guid("c0ad8b7d-49d0-4cbe-ab0f-619da96169ef"),
                            ShipName = "ПОЛАР КИНГ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("a5244bad-0a0d-4fce-b3f9-9754da33e84a"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "МЫС ДЕЖНЕВА",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("2bce1b0d-f18e-4e11-88d0-8aaed3cc2781"),
                            ShipClassId = new Guid("c0ad8b7d-49d0-4cbe-ab0f-619da96169ef"),
                            ShipName = "СЕВМОРПУТЬ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("5345b79c-07b2-4661-b7cf-26b00cf2835c"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "ГРИГОРИЙ ШЕЛИХОВ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("e5e25e3b-8c09-41b7-a844-efd04f3f1fc8"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "УРАРТУ",
                            Speed = 18.0
                        },
                        new
                        {
                            Id = new Guid("aec0beff-c031-467f-8a7f-9d4aee35cfbd"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "ФЕСКО ПАРИС",
                            Speed = 18.0
                        },
                        new
                        {
                            Id = new Guid("0d7bdaad-31b4-4ec8-bb66-5b9f4b92b0ab"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "ПРОГРЕСС",
                            Speed = 18.0
                        },
                        new
                        {
                            Id = new Guid("a1d2aefe-d38c-43d6-bead-36facc33b984"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "МИХАИЛ БРИТНЕВ",
                            Speed = 18.0
                        },
                        new
                        {
                            Id = new Guid("60af9f6f-8e38-43a4-9e3b-42f7b1771970"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "САБЕТТА",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("084a9c66-9af6-4ed7-9280-facf08f7e283"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "ГЕОРГИЙ УШАКОВ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("390a1444-4249-49a2-a971-1189b93e3e1f"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "СЕВЕРНЫЙ ПРОЕКТ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("03e210a6-0786-49b5-a25e-21aa50373663"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "БЕРИНГ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("7287433c-3adc-4161-9009-f9248ac577e3"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "ТОЛБУХИН",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("3ed0437d-02c0-4603-aa96-8328cdec4ed0"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "ЯМАЛ КРЕЧЕТ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("e8cd4778-d139-4ed4-9f88-4fd405afcfb7"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "CLEAN VISION",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("fb7bc7aa-b0a5-41d0-a8a9-28647a8ca339"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "ТИКСИ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("c046bd82-4250-466a-9b07-7fb516558283"),
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipName = "ТАЙБОЛА",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("32ea6df9-198d-4e33-8123-9c857d6e2f2b"),
                            ShipClassId = new Guid("a42cca86-9c73-4756-a88e-8de51a5281ed"),
                            ShipName = "YAMAL SPIRIT",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("9429f54f-62b3-4764-84e8-e8d3b0a1528f"),
                            ShipClassId = new Guid("a42cca86-9c73-4756-a88e-8de51a5281ed"),
                            ShipName = "НИКОЛАЙ ЧУДОТВОРЕЦ",
                            Speed = 16.0
                        });
                });

            modelBuilder.Entity("backend.Models.ShipClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ShipType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShipClass");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a42cca86-9c73-4756-a88e-8de51a5281ed"),
                            ShipType = "Without class"
                        },
                        new
                        {
                            Id = new Guid("82ea5e20-3656-4cef-895e-aeedf805f628"),
                            ShipType = "Ice1"
                        },
                        new
                        {
                            Id = new Guid("f4e126ea-58fc-45d0-9e59-58c536086757"),
                            ShipType = "Ice2"
                        },
                        new
                        {
                            Id = new Guid("d73c2602-974c-4280-9133-95613018e902"),
                            ShipType = "Ice3"
                        },
                        new
                        {
                            Id = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c"),
                            ShipType = "Arc4"
                        },
                        new
                        {
                            Id = new Guid("c0ad8b7d-49d0-4cbe-ab0f-619da96169ef"),
                            ShipType = "Arc5"
                        },
                        new
                        {
                            Id = new Guid("03c8ccd4-0a6c-4150-9dc6-ad66f1a4ed14"),
                            ShipType = "Arc6"
                        },
                        new
                        {
                            Id = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe"),
                            ShipType = "Arc7"
                        },
                        new
                        {
                            Id = new Guid("535857e4-c0dc-4640-b3ab-5ec574d79721"),
                            ShipType = "Arc9-1"
                        },
                        new
                        {
                            Id = new Guid("12b0225a-4de4-49c6-adda-10826f80fe71"),
                            ShipType = "Arc9-2"
                        });
                });

            modelBuilder.Entity("backend.Models.ShipClassIntegerClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Debuff")
                        .HasColumnType("boolean");

                    b.Property<double?>("DebuffValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("IntegerIceClassId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCanHelpMove")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCanSoloMove")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ShipClassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IntegerIceClassId");

                    b.HasIndex("ShipClassId");

                    b.ToTable("ShipClassIntegerClass");

                    b.HasData(
                        new
                        {
                            Id = new Guid("057b27d3-d7df-4019-903e-31335ab5979e"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("d314cec1-2e9d-47dd-9d64-ae99d70ae7b2"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("a42cca86-9c73-4756-a88e-8de51a5281ed")
                        },
                        new
                        {
                            Id = new Guid("90ed9605-b5c1-4973-966c-66bd55e82647"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("355e04f7-319a-47d3-87ed-81d28efb7e24"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("a42cca86-9c73-4756-a88e-8de51a5281ed")
                        },
                        new
                        {
                            Id = new Guid("9792c67a-d400-4303-8dcc-1eba4d665bf7"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("bb8a4d9b-b972-4099-a5e2-91332674fe12"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("a42cca86-9c73-4756-a88e-8de51a5281ed")
                        },
                        new
                        {
                            Id = new Guid("9267cc4b-c058-447c-9e17-21f863050e99"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("d314cec1-2e9d-47dd-9d64-ae99d70ae7b2"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("82ea5e20-3656-4cef-895e-aeedf805f628")
                        },
                        new
                        {
                            Id = new Guid("7cb4f3b2-4d06-44fa-95ee-40a8035406f2"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("355e04f7-319a-47d3-87ed-81d28efb7e24"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("82ea5e20-3656-4cef-895e-aeedf805f628")
                        },
                        new
                        {
                            Id = new Guid("45031102-2618-4134-85ba-c57d2f248755"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("bb8a4d9b-b972-4099-a5e2-91332674fe12"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("82ea5e20-3656-4cef-895e-aeedf805f628")
                        },
                        new
                        {
                            Id = new Guid("e91aa35c-bd18-41f5-9911-4805df5d7431"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("d314cec1-2e9d-47dd-9d64-ae99d70ae7b2"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("f4e126ea-58fc-45d0-9e59-58c536086757")
                        },
                        new
                        {
                            Id = new Guid("8192c0aa-572e-4282-ab8c-cc15c2976e32"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("355e04f7-319a-47d3-87ed-81d28efb7e24"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("f4e126ea-58fc-45d0-9e59-58c536086757")
                        },
                        new
                        {
                            Id = new Guid("ee5891b2-89cc-411d-b665-8674f75b31a3"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("bb8a4d9b-b972-4099-a5e2-91332674fe12"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("f4e126ea-58fc-45d0-9e59-58c536086757")
                        },
                        new
                        {
                            Id = new Guid("12cbee4a-fe07-41ca-8fe2-617f980c2d73"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("d314cec1-2e9d-47dd-9d64-ae99d70ae7b2"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("d73c2602-974c-4280-9133-95613018e902")
                        },
                        new
                        {
                            Id = new Guid("d6b16001-ee94-4db2-9fa9-491c92fbe039"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("355e04f7-319a-47d3-87ed-81d28efb7e24"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("d73c2602-974c-4280-9133-95613018e902")
                        },
                        new
                        {
                            Id = new Guid("8d2fbbf0-c816-46f4-a072-9d316a6cd998"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("bb8a4d9b-b972-4099-a5e2-91332674fe12"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("d73c2602-974c-4280-9133-95613018e902")
                        },
                        new
                        {
                            Id = new Guid("ca0a7101-ee03-4680-a0c3-f96a8815238e"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("d314cec1-2e9d-47dd-9d64-ae99d70ae7b2"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c")
                        },
                        new
                        {
                            Id = new Guid("187595e5-8054-43c6-888e-d03e8cf97229"),
                            Debuff = true,
                            DebuffValue = 0.80000000000000004,
                            IntegerIceClassId = new Guid("355e04f7-319a-47d3-87ed-81d28efb7e24"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c")
                        },
                        new
                        {
                            Id = new Guid("b9877c5c-6468-47c4-bf9f-fbf917ce9c8d"),
                            Debuff = true,
                            DebuffValue = 0.69999999999999996,
                            IntegerIceClassId = new Guid("bb8a4d9b-b972-4099-a5e2-91332674fe12"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("43f6dc17-7b29-4ab3-85d1-6588ce55b12c")
                        },
                        new
                        {
                            Id = new Guid("c2e3af23-6813-46a3-8bf6-4a09c805964e"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("d314cec1-2e9d-47dd-9d64-ae99d70ae7b2"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("c0ad8b7d-49d0-4cbe-ab0f-619da96169ef")
                        },
                        new
                        {
                            Id = new Guid("f7209f9a-0441-44d4-a14c-7c80f0640719"),
                            Debuff = true,
                            DebuffValue = 0.80000000000000004,
                            IntegerIceClassId = new Guid("355e04f7-319a-47d3-87ed-81d28efb7e24"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("c0ad8b7d-49d0-4cbe-ab0f-619da96169ef")
                        },
                        new
                        {
                            Id = new Guid("aaa17c6e-db62-4881-a100-a594f55cd499"),
                            Debuff = true,
                            DebuffValue = 0.69999999999999996,
                            IntegerIceClassId = new Guid("bb8a4d9b-b972-4099-a5e2-91332674fe12"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("c0ad8b7d-49d0-4cbe-ab0f-619da96169ef")
                        },
                        new
                        {
                            Id = new Guid("df451319-0909-4b0f-9dd5-0f8b1a2bbce1"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("d314cec1-2e9d-47dd-9d64-ae99d70ae7b2"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("03c8ccd4-0a6c-4150-9dc6-ad66f1a4ed14")
                        },
                        new
                        {
                            Id = new Guid("8db3a818-aafb-425a-8295-316825fa49e0"),
                            Debuff = true,
                            DebuffValue = 0.80000000000000004,
                            IntegerIceClassId = new Guid("355e04f7-319a-47d3-87ed-81d28efb7e24"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("03c8ccd4-0a6c-4150-9dc6-ad66f1a4ed14")
                        },
                        new
                        {
                            Id = new Guid("6330539b-95d4-4aa6-87cb-532394ccc0bc"),
                            Debuff = true,
                            DebuffValue = 0.69999999999999996,
                            IntegerIceClassId = new Guid("bb8a4d9b-b972-4099-a5e2-91332674fe12"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("03c8ccd4-0a6c-4150-9dc6-ad66f1a4ed14")
                        },
                        new
                        {
                            Id = new Guid("78f019c4-731d-40e1-b66c-f059840c726a"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("d314cec1-2e9d-47dd-9d64-ae99d70ae7b2"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe")
                        },
                        new
                        {
                            Id = new Guid("f1dfdd3a-930c-4b93-88e5-9f89aee0fea1"),
                            Debuff = true,
                            DebuffValue = 0.59999999999999998,
                            IntegerIceClassId = new Guid("355e04f7-319a-47d3-87ed-81d28efb7e24"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe")
                        },
                        new
                        {
                            Id = new Guid("0576f247-f611-43ea-a210-fe582530dba9"),
                            Debuff = true,
                            DebuffValue = 0.14999999999999999,
                            IntegerIceClassId = new Guid("bb8a4d9b-b972-4099-a5e2-91332674fe12"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("2aa5b097-ac00-4ddb-a336-277a9ed757fe")
                        },
                        new
                        {
                            Id = new Guid("ef6f0049-38ab-4a10-bd58-31d39651c59f"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("d314cec1-2e9d-47dd-9d64-ae99d70ae7b2"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("535857e4-c0dc-4640-b3ab-5ec574d79721")
                        },
                        new
                        {
                            Id = new Guid("b08aae96-7896-4891-b99a-2759d9b41174"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("355e04f7-319a-47d3-87ed-81d28efb7e24"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("535857e4-c0dc-4640-b3ab-5ec574d79721")
                        },
                        new
                        {
                            Id = new Guid("d455d29d-762f-4f8c-aa5d-058f6654e3c4"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("bb8a4d9b-b972-4099-a5e2-91332674fe12"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("535857e4-c0dc-4640-b3ab-5ec574d79721")
                        },
                        new
                        {
                            Id = new Guid("b0de5244-56a7-4294-924a-24982ac2774c"),
                            Debuff = false,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("d314cec1-2e9d-47dd-9d64-ae99d70ae7b2"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("12b0225a-4de4-49c6-adda-10826f80fe71")
                        },
                        new
                        {
                            Id = new Guid("f1707430-955d-45b8-9b4b-fcfd259aa896"),
                            Debuff = true,
                            DebuffValue = 0.90000000000000002,
                            IntegerIceClassId = new Guid("355e04f7-319a-47d3-87ed-81d28efb7e24"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("12b0225a-4de4-49c6-adda-10826f80fe71")
                        },
                        new
                        {
                            Id = new Guid("c397737e-56e9-4513-bb39-7d7677039b07"),
                            Debuff = true,
                            DebuffValue = 0.75,
                            IntegerIceClassId = new Guid("bb8a4d9b-b972-4099-a5e2-91332674fe12"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("12b0225a-4de4-49c6-adda-10826f80fe71")
                        });
                });

            modelBuilder.Entity("backend.Models.Route", b =>
                {
                    b.HasOne("backend.Models.GraphData", "Finish")
                        .WithMany()
                        .HasForeignKey("FinishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.GraphData", "Start")
                        .WithMany()
                        .HasForeignKey("StartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finish");

                    b.Navigation("Start");
                });

            modelBuilder.Entity("backend.Models.Ship", b =>
                {
                    b.HasOne("backend.Models.ShipClass", "ShipClass")
                        .WithMany("Ship")
                        .HasForeignKey("ShipClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipClass");
                });

            modelBuilder.Entity("backend.Models.ShipClassIntegerClass", b =>
                {
                    b.HasOne("backend.Models.IntegerIceClass", "IntegerIceClass")
                        .WithMany("ShipClassIntegerClasses")
                        .HasForeignKey("IntegerIceClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ShipClass", "ShipClass")
                        .WithMany("ShipClassIntegerClasses")
                        .HasForeignKey("ShipClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegerIceClass");

                    b.Navigation("ShipClass");
                });

            modelBuilder.Entity("backend.Models.IntegerIceClass", b =>
                {
                    b.Navigation("ShipClassIntegerClasses");
                });

            modelBuilder.Entity("backend.Models.ShipClass", b =>
                {
                    b.Navigation("Ship");

                    b.Navigation("ShipClassIntegerClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
