// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240607200623_AddShipData")]
    partial class AddShipData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("File");
                });

            modelBuilder.Entity("backend.Models.GraphData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RepId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GraphData");
                });

            modelBuilder.Entity("backend.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ShipClassId")
                        .HasColumnType("integer");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ShipClassId");

                    b.ToTable("Ship");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ShipClassId = 6,
                            ShipName = "ДЮК II",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = 2,
                            ShipClassId = 5,
                            ShipName = "САРМАТ",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = 3,
                            ShipClassId = 8,
                            ShipName = "EDUARD TOLL",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = 4,
                            ShipClassId = 8,
                            ShipName = "GEORGIY USHAKOV",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = 5,
                            ShipClassId = 8,
                            ShipName = "RUDOLF SAMOYLOVICH",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = 6,
                            ShipClassId = 8,
                            ShipName = "VLADIMIR VORONIN",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = 7,
                            ShipClassId = 8,
                            ShipName = "NIKOLAY YEVGENOV",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = 8,
                            ShipClassId = 8,
                            ShipName = "CHRISTOPHE DE MARGERIE",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = 9,
                            ShipClassId = 8,
                            ShipName = "BORIS VILKITSKY",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = 10,
                            ShipClassId = 6,
                            ShipName = "АРКТИКА-2",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = 11,
                            ShipClassId = 6,
                            ShipName = "ИНЖЕНЕР ВЕШНЯКОВ",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = 12,
                            ShipClassId = 5,
                            ShipName = "ТАМБЕЙ",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = 13,
                            ShipClassId = 8,
                            ShipName = "ШТУРМАН АЛЬБАНОВ",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = 14,
                            ShipClassId = 5,
                            ShipName = "НИКИФОР БЕГИЧЕВ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = 15,
                            ShipClassId = 8,
                            ShipName = "НОРИЛЬСКИЙ НИКЕЛЬ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = 16,
                            ShipClassId = 6,
                            ShipName = "АЙС ИГЛ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = 17,
                            ShipClassId = 8,
                            ShipName = "ШТУРМАН КОШЕЛЕВ",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = 18,
                            ShipClassId = 8,
                            ShipName = "ШТУРМАН ЩЕРБИНИН",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = 19,
                            ShipClassId = 8,
                            ShipName = "ШТУРМАН СКУРАТОВ",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = 20,
                            ShipClassId = 6,
                            ShipName = "ИОГАНН МАХМАСТАЛЬ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = 21,
                            ShipClassId = 8,
                            ShipName = "BORIS SOKOLOV",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = 22,
                            ShipClassId = 6,
                            ShipName = "ИНЖЕНЕР ТРУБИН",
                            Speed = 12.0
                        },
                        new
                        {
                            Id = 23,
                            ShipClassId = 5,
                            ShipName = "БАРЕНЦ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = 24,
                            ShipClassId = 6,
                            ShipName = "ПОЛАР КИНГ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = 25,
                            ShipClassId = 5,
                            ShipName = "МЫС ДЕЖНЕВА",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = 26,
                            ShipClassId = 6,
                            ShipName = "СЕВМОРПУТЬ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = 27,
                            ShipClassId = 5,
                            ShipName = "ГРИГОРИЙ ШЕЛИХОВ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = 28,
                            ShipClassId = 5,
                            ShipName = "УРАРТУ",
                            Speed = 18.0
                        },
                        new
                        {
                            Id = 29,
                            ShipClassId = 5,
                            ShipName = "ФЕСКО ПАРИС",
                            Speed = 18.0
                        },
                        new
                        {
                            Id = 30,
                            ShipClassId = 5,
                            ShipName = "ПРОГРЕСС",
                            Speed = 18.0
                        },
                        new
                        {
                            Id = 31,
                            ShipClassId = 5,
                            ShipName = "МИХАИЛ БРИТНЕВ",
                            Speed = 18.0
                        },
                        new
                        {
                            Id = 32,
                            ShipClassId = 5,
                            ShipName = "САБЕТТА",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = 33,
                            ShipClassId = 5,
                            ShipName = "ГЕОРГИЙ УШАКОВ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = 34,
                            ShipClassId = 5,
                            ShipName = "СЕВЕРНЫЙ ПРОЕКТ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = 36,
                            ShipClassId = 5,
                            ShipName = "БЕРИНГ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = 37,
                            ShipClassId = 5,
                            ShipName = "ТОЛБУХИН",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = 38,
                            ShipClassId = 5,
                            ShipName = "ЯМАЛ КРЕЧЕТ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = 39,
                            ShipClassId = 5,
                            ShipName = "CLEAN VISION",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = 41,
                            ShipClassId = 5,
                            ShipName = "ТИКСИ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = 42,
                            ShipClassId = 5,
                            ShipName = "ТАЙБОЛА",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = 40,
                            ShipClassId = 1,
                            ShipName = "YAMAL SPIRIT",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = 35,
                            ShipClassId = 1,
                            ShipName = "НИКОЛАЙ ЧУДОТВОРЕЦ",
                            Speed = 16.0
                        });
                });

            modelBuilder.Entity("backend.Models.ShipClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ShipType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShipClass");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ShipType = "Without class"
                        },
                        new
                        {
                            Id = 2,
                            ShipType = "Ice1"
                        },
                        new
                        {
                            Id = 3,
                            ShipType = "Ice2"
                        },
                        new
                        {
                            Id = 4,
                            ShipType = "Ice3"
                        },
                        new
                        {
                            Id = 5,
                            ShipType = "Arc4"
                        },
                        new
                        {
                            Id = 6,
                            ShipType = "Arc5"
                        },
                        new
                        {
                            Id = 7,
                            ShipType = "Arc6"
                        },
                        new
                        {
                            Id = 8,
                            ShipType = "Arc7"
                        },
                        new
                        {
                            Id = 9,
                            ShipType = "Arc9-1"
                        },
                        new
                        {
                            Id = 10,
                            ShipType = "Arc9-2"
                        });
                });

            modelBuilder.Entity("backend.Models.Ship", b =>
                {
                    b.HasOne("backend.Models.ShipClass", "ShipClass")
                        .WithMany("Ship")
                        .HasForeignKey("ShipClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipClass");
                });

            modelBuilder.Entity("backend.Models.ShipClass", b =>
                {
                    b.Navigation("Ship");
                });
#pragma warning restore 612, 618
        }
    }
}
