// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240610185205_addDebuffHelpValue")]
    partial class addDebuffHelpValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("File");
                });

            modelBuilder.Entity("backend.Models.GraphData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RepId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GraphData");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f22f5534-fb00-4bc0-bbbe-8323c96f83f4"),
                            Latitude = 73.099999999999994,
                            Longitude = 80.0,
                            PointName = "Бухта Север и Диксон",
                            RepId = 1010
                        },
                        new
                        {
                            Id = new Guid("7aed3e74-3ac7-4023-822c-015f1a02a1f7"),
                            Latitude = 69.400000000000006,
                            Longitude = 86.150000000000006,
                            PointName = "Дудинка",
                            RepId = 1007
                        },
                        new
                        {
                            Id = new Guid("212bd650-8044-4eac-a7f0-2de2e5418055"),
                            Latitude = 69.900000000000006,
                            Longitude = 44.600000000000001,
                            PointName = "кромка льда на Западе",
                            RepId = 2002
                        },
                        new
                        {
                            Id = new Guid("1da5593d-3452-4d4f-8512-f72edc18dd24"),
                            Latitude = 69.150000000000006,
                            Longitude = 57.68,
                            PointName = "Варандей-Приразломное",
                            RepId = 1015
                        },
                        new
                        {
                            Id = new Guid("8fbdc683-dbb0-4dbe-b067-1f0d16ae1b84"),
                            Latitude = 73.0,
                            Longitude = 44.0,
                            PointName = "Штокман",
                            RepId = 1012
                        },
                        new
                        {
                            Id = new Guid("908e6cd9-721f-4059-8524-1446f20fa76e"),
                            Latitude = 71.5,
                            Longitude = 22.0,
                            PointName = "Окно в Европу",
                            RepId = 2001
                        },
                        new
                        {
                            Id = new Guid("a5be7d44-5aae-45e2-9b49-c4feae163087"),
                            Latitude = 74.599999999999994,
                            Longitude = 63.899999999999999,
                            PointName = "Победа месторождение",
                            RepId = 1011
                        },
                        new
                        {
                            Id = new Guid("912db1e3-dd28-4b1e-a1b2-fe293ef54195"),
                            Latitude = 76.400000000000006,
                            Longitude = 86.400000000000006,
                            PointName = "Карское - 3 (центр)",
                            RepId = 2008
                        },
                        new
                        {
                            Id = new Guid("f92a5462-0f86-427c-af3d-9a060541e10f"),
                            Latitude = 77.599999999999994,
                            Longitude = 107.7,
                            PointName = "пролив Вилькицкого - 3",
                            RepId = 2013
                        },
                        new
                        {
                            Id = new Guid("d85f10f1-d061-408c-ad99-5f138d19d51a"),
                            Latitude = 74.900000000000006,
                            Longitude = 116.7,
                            PointName = "Лаптевых - 4 (юг)",
                            RepId = 2018
                        },
                        new
                        {
                            Id = new Guid("6090c875-5ff3-4959-a9b4-bf7b91973936"),
                            Latitude = 73.099999999999994,
                            Longitude = 72.700000000000003,
                            PointName = "Вход в Обскую губу",
                            RepId = 2009
                        },
                        new
                        {
                            Id = new Guid("175ace30-a421-4cd3-8edf-747ae9fd6e0c"),
                            Latitude = 68.5,
                            Longitude = 73.700000000000003,
                            PointName = "Новый порт",
                            RepId = 1004
                        },
                        new
                        {
                            Id = new Guid("c14656ee-3369-496a-ad7c-e45bca03af39"),
                            Latitude = 76.75,
                            Longitude = 116.0,
                            PointName = "Лаптевых - 1 (центр)",
                            RepId = 2015
                        },
                        new
                        {
                            Id = new Guid("99eee87a-44f0-4c58-8280-b2841a7877ca"),
                            Latitude = 74.0,
                            Longitude = 76.700000000000003,
                            PointName = "Карское - 1 (сбор каравана)",
                            RepId = 2006
                        },
                        new
                        {
                            Id = new Guid("f6ebbc76-8e0d-47a6-952c-7b96cd7608b0"),
                            Latitude = 72.349999999999994,
                            Longitude = 79.599999999999994,
                            PointName = "Лескинское м-е",
                            RepId = 1014
                        },
                        new
                        {
                            Id = new Guid("773dc3d2-e99d-4961-bacc-e48ee2077e97"),
                            Latitude = 70.299999999999997,
                            Longitude = 57.799999999999997,
                            PointName = "Карские ворота",
                            RepId = 2005
                        },
                        new
                        {
                            Id = new Guid("ea00f8af-6563-47a5-b18c-cfa158992574"),
                            Latitude = 77.299999999999997,
                            Longitude = 67.700000000000003,
                            PointName = "Мыс Желания",
                            RepId = 2003
                        },
                        new
                        {
                            Id = new Guid("89e8c2a2-20a6-4d42-8e54-4b06557149ba"),
                            Latitude = 71.739999999999995,
                            Longitude = 184.69999999999999,
                            PointName = "остров Врангеля",
                            RepId = 2026
                        },
                        new
                        {
                            Id = new Guid("2b65edc1-a17b-4b1e-aa7d-f71015529504"),
                            Latitude = 70.700000000000003,
                            Longitude = 170.5,
                            PointName = "Восточно-Сибирское - 1 (восток)",
                            RepId = 2023
                        },
                        new
                        {
                            Id = new Guid("bb91bbf3-a7f9-4a42-9f28-d243e2ad2385"),
                            Latitude = 77.799999999999997,
                            Longitude = 104.09999999999999,
                            PointName = "пролив Вилькицкого - восток",
                            RepId = 2012
                        },
                        new
                        {
                            Id = new Guid("677ba9cb-b788-43db-b112-424a97897b68"),
                            Latitude = 77.700000000000003,
                            Longitude = 99.5,
                            PointName = "пролив Вилькицкого - запад",
                            RepId = 2011
                        },
                        new
                        {
                            Id = new Guid("dd11d2b1-4aad-4bbc-8d2c-ee1fdf7016d5"),
                            Latitude = 76.200000000000003,
                            Longitude = 58.299999999999997,
                            PointName = "около Новой Земли",
                            RepId = 2004
                        },
                        new
                        {
                            Id = new Guid("1dc4ae04-bed8-43e8-b2a0-edecdccc8604"),
                            Latitude = 74.400000000000006,
                            Longitude = 139.0,
                            PointName = "Пролив Санникова - 1",
                            RepId = 2020
                        },
                        new
                        {
                            Id = new Guid("0b1181cd-caed-4b02-9f5b-f28f9a6f5024"),
                            Latitude = 74.299999999999997,
                            Longitude = 146.69999999999999,
                            PointName = "Пролив Санникова - 2",
                            RepId = 2021
                        },
                        new
                        {
                            Id = new Guid("380e1a71-50a4-498d-bf47-cb4d80e54557"),
                            Latitude = 74.0,
                            Longitude = 128.09999999999999,
                            PointName = "устье Лены",
                            RepId = 2019
                        },
                        new
                        {
                            Id = new Guid("aaa7523d-872e-45c2-82b7-77418ba0db76"),
                            Latitude = 71.299999999999997,
                            Longitude = 72.150000000000006,
                            PointName = "Сабетта",
                            RepId = 1003
                        },
                        new
                        {
                            Id = new Guid("efbb7c6a-3952-41f7-992b-89fa17036f7e"),
                            Latitude = 69.099999999999994,
                            Longitude = 169.40000000000001,
                            PointName = "мыс.Наглёйнын",
                            RepId = 1009
                        },
                        new
                        {
                            Id = new Guid("82a602e8-3292-4abd-b789-49881648560e"),
                            Latitude = 69.900000000000006,
                            Longitude = 179.0,
                            PointName = "пролив Лонга",
                            RepId = 2027
                        },
                        new
                        {
                            Id = new Guid("ad1b7ade-f60d-42de-bd26-245b5c2896bf"),
                            Latitude = 73.5,
                            Longitude = 169.90000000000001,
                            PointName = "Восточно-Сибирское - 3 (север)",
                            RepId = 2025
                        },
                        new
                        {
                            Id = new Guid("573213e7-9b15-4163-bbf1-72b349759c0b"),
                            Latitude = 64.950000000000003,
                            Longitude = 40.049999999999997,
                            PointName = "Архангельск",
                            RepId = 1002
                        },
                        new
                        {
                            Id = new Guid("318b2da2-955a-4d4c-925d-d55fe0f31bc9"),
                            Latitude = 75.900000000000006,
                            Longitude = 152.59999999999999,
                            PointName = "Лаптевых - 3 (восток)",
                            RepId = 2017
                        },
                        new
                        {
                            Id = new Guid("3b675438-4445-4e3a-acd3-53d735a8684e"),
                            Latitude = 68.370000000000005,
                            Longitude = 54.600000000000001,
                            PointName = "МОТ Печора",
                            RepId = 1017
                        },
                        new
                        {
                            Id = new Guid("4e22adf2-ac5c-43b6-b635-9350ad67a520"),
                            Latitude = 73.700000000000003,
                            Longitude = 109.26000000000001,
                            PointName = "Хатангский залив",
                            RepId = 1008
                        },
                        new
                        {
                            Id = new Guid("69e444bb-7a08-4464-8604-7e75dc1d232e"),
                            Latitude = 72.0,
                            Longitude = 159.5,
                            PointName = "Восточно-Сибирское - 2 (запад)",
                            RepId = 2024
                        },
                        new
                        {
                            Id = new Guid("9f020b65-4ca5-4e71-9041-23d73ac61b7d"),
                            Latitude = 72.400000000000006,
                            Longitude = 65.599999999999994,
                            PointName = "Ленинградское-Русановское",
                            RepId = 1013
                        },
                        new
                        {
                            Id = new Guid("4bd1b071-9688-442a-94a8-16afbd3f1f7f"),
                            Latitude = 71.0,
                            Longitude = 73.730000000000004,
                            PointName = "терминал Утренний",
                            RepId = 1005
                        },
                        new
                        {
                            Id = new Guid("0a152046-e1a7-4308-8728-8ba0e65cb80a"),
                            Latitude = 76.5,
                            Longitude = 97.599999999999994,
                            PointName = "Таймырский залив",
                            RepId = 2010
                        },
                        new
                        {
                            Id = new Guid("22a5591b-75ab-43af-9393-86011e2406df"),
                            Latitude = 64.200000000000003,
                            Longitude = 188.19999999999999,
                            PointName = "Берингово",
                            RepId = 2029
                        },
                        new
                        {
                            Id = new Guid("1a093f21-0e22-47b8-ab06-78a94e047daa"),
                            Latitude = 60.700000000000003,
                            Longitude = 175.30000000000001,
                            PointName = "кромка льда на Востоке",
                            RepId = 2030
                        },
                        new
                        {
                            Id = new Guid("426c9e66-6e72-46a9-9eea-b3f0405453d2"),
                            Latitude = 69.75,
                            Longitude = 169.90000000000001,
                            PointName = "Рейд Певек",
                            RepId = 1006
                        },
                        new
                        {
                            Id = new Guid("6c6d0b7e-8b8f-42a6-a2ec-b018b80e81f8"),
                            Latitude = 75.5,
                            Longitude = 131.5,
                            PointName = "Лаптевых - 2 (центр)",
                            RepId = 2016
                        },
                        new
                        {
                            Id = new Guid("db51c0e2-be6a-44f5-9c7f-95c44b0a044e"),
                            Latitude = 69.5,
                            Longitude = 33.75,
                            PointName = "Рейд Мурманска",
                            RepId = 1001
                        },
                        new
                        {
                            Id = new Guid("451a0a00-712a-4e54-bcc3-a4892c7e5e16"),
                            Latitude = 76.700000000000003,
                            Longitude = 140.80000000000001,
                            PointName = "остров Котельный",
                            RepId = 2022
                        },
                        new
                        {
                            Id = new Guid("4936ca2d-e5cc-4e90-ab86-783d26d1d0d4"),
                            Latitude = 74.799999999999997,
                            Longitude = 84.200000000000003,
                            PointName = "Карское - 2 (прибрежный)",
                            RepId = 2007
                        },
                        new
                        {
                            Id = new Guid("64f9ce3a-0e18-4000-b4cc-402c18c57682"),
                            Latitude = 67.579999999999998,
                            Longitude = 47.82,
                            PointName = "Индига",
                            RepId = 1016
                        },
                        new
                        {
                            Id = new Guid("477268b0-ee0b-4105-a95a-02d927fd70b4"),
                            Latitude = 65.900000000000006,
                            Longitude = -169.34999999999999,
                            PointName = "Берингов пролив",
                            RepId = 2028
                        },
                        new
                        {
                            Id = new Guid("2abfb1f0-5669-4fb5-9b3c-e3ce6dbeb561"),
                            Latitude = 55.700000000000003,
                            Longitude = 164.25,
                            PointName = "Окно в Азию",
                            RepId = 2031
                        });
                });

            modelBuilder.Entity("backend.Models.IntegerIceClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("MinSpeed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("IntegerIceClass");

                    b.HasData(
                        new
                        {
                            Id = new Guid("273502cb-25c1-4811-aa80-7f6fa487daed"),
                            MaxSpeed = 21,
                            MinSpeed = 20
                        },
                        new
                        {
                            Id = new Guid("2c6b5909-cab9-43c0-9035-20513bcfa901"),
                            MaxSpeed = 19,
                            MinSpeed = 15
                        },
                        new
                        {
                            Id = new Guid("96e66895-a43d-4e62-9ae4-c1c7e939b125"),
                            MaxSpeed = 14,
                            MinSpeed = 10
                        });
                });

            modelBuilder.Entity("backend.Models.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FinishId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Length")
                        .HasColumnType("double precision");

                    b.Property<Guid>("StartId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StatusRoute")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FinishId");

                    b.HasIndex("StartId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12578bd3-141c-4ae5-a65e-6ebfc7bb1416"),
                            FinishId = new Guid("773dc3d2-e99d-4961-bacc-e48ee2077e97"),
                            Length = 270.01664160000001,
                            StartId = new Guid("64f9ce3a-0e18-4000-b4cc-402c18c57682"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("c834c4a4-4725-45b9-9907-3057ac159403"),
                            FinishId = new Guid("175ace30-a421-4cd3-8edf-747ae9fd6e0c"),
                            Length = 277.18983630000002,
                            StartId = new Guid("6090c875-5ff3-4959-a9b4-bf7b91973936"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("2ed130f9-e047-4739-88e5-51390fd27755"),
                            FinishId = new Guid("426c9e66-6e72-46a9-9eea-b3f0405453d2"),
                            Length = 58.390351320000001,
                            StartId = new Guid("2b65edc1-a17b-4b1e-aa7d-f71015529504"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("2f20b0b6-376a-4548-ac23-4842b6fe002e"),
                            FinishId = new Guid("ea00f8af-6563-47a5-b18c-cfa158992574"),
                            Length = 238.85898850000001,
                            StartId = new Guid("99eee87a-44f0-4c58-8280-b2841a7877ca"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("42122b9f-150d-4161-83ea-656898e7dcb2"),
                            FinishId = new Guid("99eee87a-44f0-4c58-8280-b2841a7877ca"),
                            Length = 86.930049159999996,
                            StartId = new Guid("6090c875-5ff3-4959-a9b4-bf7b91973936"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("b294651d-1d33-4763-bf12-20c382018155"),
                            FinishId = new Guid("908e6cd9-721f-4059-8524-1446f20fa76e"),
                            Length = 655.35573739999995,
                            StartId = new Guid("dd11d2b1-4aad-4bbc-8d2c-ee1fdf7016d5"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("f4de17b4-14b1-40ea-b903-51c25b31d288"),
                            FinishId = new Guid("908e6cd9-721f-4059-8524-1446f20fa76e"),
                            Length = 410.57011160000002,
                            StartId = new Guid("8fbdc683-dbb0-4dbe-b067-1f0d16ae1b84"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("1e564729-3ae3-4e2b-a4ec-a1896fbaa5d3"),
                            FinishId = new Guid("22a5591b-75ab-43af-9393-86011e2406df"),
                            Length = 119.56344919999999,
                            StartId = new Guid("477268b0-ee0b-4105-a95a-02d927fd70b4"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("d8ad2483-3eb5-4b79-b3db-5ce78c92623f"),
                            FinishId = new Guid("912db1e3-dd28-4b1e-a1b2-fe293ef54195"),
                            Length = 206.8821279,
                            StartId = new Guid("99eee87a-44f0-4c58-8280-b2841a7877ca"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("17793ccd-c53d-45ed-8395-8f3d2a5e57a5"),
                            FinishId = new Guid("380e1a71-50a4-498d-bf47-cb4d80e54557"),
                            Length = 191.1526107,
                            StartId = new Guid("d85f10f1-d061-408c-ad99-5f138d19d51a"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("540d3259-4ffd-4974-a2d6-623fc53f0ef8"),
                            FinishId = new Guid("2b65edc1-a17b-4b1e-aa7d-f71015529504"),
                            Length = 178.64541199999999,
                            StartId = new Guid("82a602e8-3292-4abd-b789-49881648560e"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("e6ec8bad-f357-4a13-afed-9de8ee8edcee"),
                            FinishId = new Guid("69e444bb-7a08-4464-8604-7e75dc1d232e"),
                            Length = 205.7748943,
                            StartId = new Guid("ad1b7ade-f60d-42de-bd26-245b5c2896bf"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("b069a828-725f-4dc2-99cb-14da972d0fd2"),
                            FinishId = new Guid("1dc4ae04-bed8-43e8-b2a0-edecdccc8604"),
                            Length = 134.30498470000001,
                            StartId = new Guid("6c6d0b7e-8b8f-42a6-a2ec-b018b80e81f8"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("6c80624c-5e4e-4526-a842-40535117a24e"),
                            FinishId = new Guid("318b2da2-955a-4d4c-925d-d55fe0f31bc9"),
                            Length = 174.3916815,
                            StartId = new Guid("451a0a00-712a-4e54-bcc3-a4892c7e5e16"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("3893386e-163f-4be5-9786-22cd8f538065"),
                            FinishId = new Guid("1da5593d-3452-4d4f-8512-f72edc18dd24"),
                            Length = 81.815960799999999,
                            StartId = new Guid("3b675438-4445-4e3a-acd3-53d735a8684e"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("1a9751ea-65b8-4319-b02b-7495dadfc7fe"),
                            FinishId = new Guid("4936ca2d-e5cc-4e90-ab86-783d26d1d0d4"),
                            Length = 123.6831421,
                            StartId = new Guid("f22f5534-fb00-4bc0-bbbe-8323c96f83f4"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("b3982dff-655b-476d-8fd1-75fd190ae7f8"),
                            FinishId = new Guid("380e1a71-50a4-498d-bf47-cb4d80e54557"),
                            Length = 246.24586489999999,
                            StartId = new Guid("c14656ee-3369-496a-ad7c-e45bca03af39"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("74e6289e-b790-4104-99c7-64e5a44ecc3c"),
                            FinishId = new Guid("451a0a00-712a-4e54-bcc3-a4892c7e5e16"),
                            Length = 339.77822600000002,
                            StartId = new Guid("c14656ee-3369-496a-ad7c-e45bca03af39"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("96c4c698-b315-43d2-a7f0-b217e4d473e1"),
                            FinishId = new Guid("212bd650-8044-4eac-a7f0-2de2e5418055"),
                            Length = 270.59211690000001,
                            StartId = new Guid("773dc3d2-e99d-4961-bacc-e48ee2077e97"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("9020b580-d704-47b1-9e12-f024499e1b38"),
                            FinishId = new Guid("4bd1b071-9688-442a-94a8-16afbd3f1f7f"),
                            Length = 127.65462359999999,
                            StartId = new Guid("6090c875-5ff3-4959-a9b4-bf7b91973936"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("1b6a88f5-f570-4a0c-923f-f3c7b5618b73"),
                            FinishId = new Guid("4e22adf2-ac5c-43b6-b635-9350ad67a520"),
                            Length = 140.73600680000001,
                            StartId = new Guid("d85f10f1-d061-408c-ad99-5f138d19d51a"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("f6bf4248-81c6-44f6-9f3f-cac35b6d7161"),
                            FinishId = new Guid("1da5593d-3452-4d4f-8512-f72edc18dd24"),
                            Length = 278.1227556,
                            StartId = new Guid("212bd650-8044-4eac-a7f0-2de2e5418055"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("f4dc2c9c-ba70-401e-9da2-96c4b858f888"),
                            FinishId = new Guid("7aed3e74-3ac7-4023-822c-015f1a02a1f7"),
                            Length = 251.86265969999999,
                            StartId = new Guid("f22f5534-fb00-4bc0-bbbe-8323c96f83f4"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("7537dc37-a11b-4a89-bd8e-2aa6518ab794"),
                            FinishId = new Guid("2b65edc1-a17b-4b1e-aa7d-f71015529504"),
                            Length = 225.02389769999999,
                            StartId = new Guid("69e444bb-7a08-4464-8604-7e75dc1d232e"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("b1d300f9-cd87-4085-b0ef-a28431beead7"),
                            FinishId = new Guid("451a0a00-712a-4e54-bcc3-a4892c7e5e16"),
                            Length = 152.20194660000001,
                            StartId = new Guid("6c6d0b7e-8b8f-42a6-a2ec-b018b80e81f8"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("c208dded-e3b4-4b5a-a5e8-442b5a4fe9e4"),
                            FinishId = new Guid("db51c0e2-be6a-44f5-9c7f-95c44b0a044e"),
                            Length = 288.19191749999999,
                            StartId = new Guid("8fbdc683-dbb0-4dbe-b067-1f0d16ae1b84"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("8e412b67-0a3d-425d-8318-0f9910db4d65"),
                            FinishId = new Guid("c14656ee-3369-496a-ad7c-e45bca03af39"),
                            Length = 121.8205679,
                            StartId = new Guid("f92a5462-0f86-427c-af3d-9a060541e10f"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("120de633-9237-46d1-9646-54ddccb8ba3e"),
                            FinishId = new Guid("573213e7-9b15-4163-bbf1-72b349759c0b"),
                            Length = 315.30476279999999,
                            StartId = new Guid("212bd650-8044-4eac-a7f0-2de2e5418055"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("10114c5c-e95b-4076-aea8-9065e8043399"),
                            FinishId = new Guid("1da5593d-3452-4d4f-8512-f72edc18dd24"),
                            Length = 69.168612730000007,
                            StartId = new Guid("773dc3d2-e99d-4961-bacc-e48ee2077e97"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("34e70c57-159d-4377-a44e-a9f0e28d871f"),
                            FinishId = new Guid("6c6d0b7e-8b8f-42a6-a2ec-b018b80e81f8"),
                            Length = 234.89411480000001,
                            StartId = new Guid("c14656ee-3369-496a-ad7c-e45bca03af39"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("2db162df-f513-4811-af08-1744b583c1d7"),
                            FinishId = new Guid("f92a5462-0f86-427c-af3d-9a060541e10f"),
                            Length = 47.63018916,
                            StartId = new Guid("bb91bbf3-a7f9-4a42-9f28-d243e2ad2385"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("12931c7f-7b20-448b-acf3-3e9564ed4a37"),
                            FinishId = new Guid("318b2da2-955a-4d4c-925d-d55fe0f31bc9"),
                            Length = 308.41519959999999,
                            StartId = new Guid("ad1b7ade-f60d-42de-bd26-245b5c2896bf"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("65836f82-aed5-4508-b2d1-61cbdc71e164"),
                            FinishId = new Guid("f22f5534-fb00-4bc0-bbbe-8323c96f83f4"),
                            Length = 77.963962300000006,
                            StartId = new Guid("99eee87a-44f0-4c58-8280-b2841a7877ca"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("b67f563f-71df-4433-964e-6e9d3b442f02"),
                            FinishId = new Guid("212bd650-8044-4eac-a7f0-2de2e5418055"),
                            Length = 445.92813819999998,
                            StartId = new Guid("dd11d2b1-4aad-4bbc-8d2c-ee1fdf7016d5"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("ac1888a1-5a59-42a0-8a44-98746d6ccff0"),
                            FinishId = new Guid("2b65edc1-a17b-4b1e-aa7d-f71015529504"),
                            Length = 436.27169129999999,
                            StartId = new Guid("318b2da2-955a-4d4c-925d-d55fe0f31bc9"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("48446a98-284c-4587-af89-8527e0001e17"),
                            FinishId = new Guid("d85f10f1-d061-408c-ad99-5f138d19d51a"),
                            Length = 229.4577372,
                            StartId = new Guid("6c6d0b7e-8b8f-42a6-a2ec-b018b80e81f8"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("2b982e36-c955-4415-9a8f-edbe97b5b003"),
                            FinishId = new Guid("8fbdc683-dbb0-4dbe-b067-1f0d16ae1b84"),
                            Length = 297.15080849999998,
                            StartId = new Guid("dd11d2b1-4aad-4bbc-8d2c-ee1fdf7016d5"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("48c40ff0-f296-481c-8f5a-5f2d00a0bea4"),
                            FinishId = new Guid("9f020b65-4ca5-4e71-9041-23d73ac61b7d"),
                            Length = 296.3206745,
                            StartId = new Guid("ea00f8af-6563-47a5-b18c-cfa158992574"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("855abdc5-a5ae-4e4f-8db4-b6a84ecdca8f"),
                            FinishId = new Guid("89e8c2a2-20a6-4d42-8e54-4b06557149ba"),
                            Length = 373.63082739999999,
                            StartId = new Guid("477268b0-ee0b-4105-a95a-02d927fd70b4"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("04ae9b25-461b-464d-881d-1bc317c948fc"),
                            FinishId = new Guid("2b65edc1-a17b-4b1e-aa7d-f71015529504"),
                            Length = 281.08704540000002,
                            StartId = new Guid("89e8c2a2-20a6-4d42-8e54-4b06557149ba"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("750940a2-6111-4583-8243-3b11ca6aa90e"),
                            FinishId = new Guid("efbb7c6a-3952-41f7-992b-89fa17036f7e"),
                            Length = 98.815529369999993,
                            StartId = new Guid("2b65edc1-a17b-4b1e-aa7d-f71015529504"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("46249ab6-f2b8-4463-b56d-9a0a31dd48b7"),
                            FinishId = new Guid("2abfb1f0-5669-4fb5-9b3c-e3ce6dbeb561"),
                            Length = 460.28483269999998,
                            StartId = new Guid("1a093f21-0e22-47b8-ab06-78a94e047daa"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("c757a741-4a8a-460c-ae28-957356fa53e1"),
                            FinishId = new Guid("69e444bb-7a08-4464-8604-7e75dc1d232e"),
                            Length = 260.57011360000001,
                            StartId = new Guid("318b2da2-955a-4d4c-925d-d55fe0f31bc9"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("a180eb3a-9717-4b8b-a0d8-b800cee066a1"),
                            FinishId = new Guid("1dc4ae04-bed8-43e8-b2a0-edecdccc8604"),
                            Length = 179.7422785,
                            StartId = new Guid("380e1a71-50a4-498d-bf47-cb4d80e54557"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("d53f62ec-f1ec-4477-8c3d-ab692c2ce1cd"),
                            FinishId = new Guid("ea00f8af-6563-47a5-b18c-cfa158992574"),
                            Length = 263.63934649999999,
                            StartId = new Guid("6090c875-5ff3-4959-a9b4-bf7b91973936"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("a856ff7e-993c-4bde-aab2-8e74748a4fb6"),
                            FinishId = new Guid("477268b0-ee0b-4105-a95a-02d927fd70b4"),
                            Length = 355.62316140000001,
                            StartId = new Guid("82a602e8-3292-4abd-b789-49881648560e"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("a6944fa9-f8f9-4c1c-832f-c3c910afcffc"),
                            FinishId = new Guid("0a152046-e1a7-4308-8728-8ba0e65cb80a"),
                            Length = 157.6035239,
                            StartId = new Guid("912db1e3-dd28-4b1e-a1b2-fe293ef54195"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("03ce543e-4951-48c2-a4ca-b9dc5fe11067"),
                            FinishId = new Guid("677ba9cb-b788-43db-b112-424a97897b68"),
                            Length = 192.45222290000001,
                            StartId = new Guid("912db1e3-dd28-4b1e-a1b2-fe293ef54195"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("50c6f3d1-d65d-4081-bdfc-a5c91bf74dad"),
                            FinishId = new Guid("99eee87a-44f0-4c58-8280-b2841a7877ca"),
                            Length = 215.05323759999999,
                            StartId = new Guid("9f020b65-4ca5-4e71-9041-23d73ac61b7d"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("d6c21220-fe33-4cce-81a5-1cfedeff23e6"),
                            FinishId = new Guid("0a152046-e1a7-4308-8728-8ba0e65cb80a"),
                            Length = 223.5714878,
                            StartId = new Guid("4936ca2d-e5cc-4e90-ab86-783d26d1d0d4"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("e7c48e58-11ae-40e4-9084-5738f0550951"),
                            FinishId = new Guid("912db1e3-dd28-4b1e-a1b2-fe293ef54195"),
                            Length = 352.93682100000001,
                            StartId = new Guid("a5be7d44-5aae-45e2-9b49-c4feae163087"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("eab2bc0e-93d0-4fde-b97c-869c3e4afed7"),
                            FinishId = new Guid("aaa7523d-872e-45c2-82b7-77418ba0db76"),
                            Length = 108.6630553,
                            StartId = new Guid("6090c875-5ff3-4959-a9b4-bf7b91973936"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("76eaff2d-b62e-4388-8056-d4875947ce3a"),
                            FinishId = new Guid("1a093f21-0e22-47b8-ab06-78a94e047daa"),
                            Length = 414.6912251,
                            StartId = new Guid("22a5591b-75ab-43af-9393-86011e2406df"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("40bb81e0-d9a7-4f5a-838f-11431f5b7c15"),
                            FinishId = new Guid("773dc3d2-e99d-4961-bacc-e48ee2077e97"),
                            Length = 410.45491850000002,
                            StartId = new Guid("99eee87a-44f0-4c58-8280-b2841a7877ca"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("44ecc2b1-1a81-491d-bc67-04e68b17621e"),
                            FinishId = new Guid("ea00f8af-6563-47a5-b18c-cfa158992574"),
                            Length = 260.1771091,
                            StartId = new Guid("912db1e3-dd28-4b1e-a1b2-fe293ef54195"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("7b0a568c-fb8d-422c-a77c-e5e1f6359180"),
                            FinishId = new Guid("ea00f8af-6563-47a5-b18c-cfa158992574"),
                            Length = 171.4172136,
                            StartId = new Guid("a5be7d44-5aae-45e2-9b49-c4feae163087"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("ea38f51e-4e16-465a-907e-e560ded0389e"),
                            FinishId = new Guid("bb91bbf3-a7f9-4a42-9f28-d243e2ad2385"),
                            Length = 116.7439955,
                            StartId = new Guid("0a152046-e1a7-4308-8728-8ba0e65cb80a"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("88962365-d1f5-4c3b-9c06-f2548b62145a"),
                            FinishId = new Guid("0b1181cd-caed-4b02-9f5b-f28f9a6f5024"),
                            Length = 261.60058900000001,
                            StartId = new Guid("69e444bb-7a08-4464-8604-7e75dc1d232e"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("9118c047-5ec4-4558-aecd-ae819834c0c6"),
                            FinishId = new Guid("ea00f8af-6563-47a5-b18c-cfa158992574"),
                            Length = 409.31115749999998,
                            StartId = new Guid("677ba9cb-b788-43db-b112-424a97897b68"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("fbdf4d08-a159-4116-b0de-a74707141ee9"),
                            FinishId = new Guid("773dc3d2-e99d-4961-bacc-e48ee2077e97"),
                            Length = 326.43284169999998,
                            StartId = new Guid("6090c875-5ff3-4959-a9b4-bf7b91973936"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("4c94fc75-dbad-4b35-923b-e8a4ab3b1bcf"),
                            FinishId = new Guid("773dc3d2-e99d-4961-bacc-e48ee2077e97"),
                            Length = 195.73284430000001,
                            StartId = new Guid("9f020b65-4ca5-4e71-9041-23d73ac61b7d"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("d2de1dab-b18b-4c2d-a4f1-a1e8361d62ac"),
                            FinishId = new Guid("212bd650-8044-4eac-a7f0-2de2e5418055"),
                            Length = 156.0644819,
                            StartId = new Guid("64f9ce3a-0e18-4000-b4cc-402c18c57682"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("2dc5170e-cde1-4e4e-9a6e-62b243e920fe"),
                            FinishId = new Guid("f22f5534-fb00-4bc0-bbbe-8323c96f83f4"),
                            Length = 45.642155700000004,
                            StartId = new Guid("f6ebbc76-8e0d-47a6-952c-7b96cd7608b0"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("236ae9e5-bd9c-459e-af7e-7cac49eb82b2"),
                            FinishId = new Guid("d85f10f1-d061-408c-ad99-5f138d19d51a"),
                            Length = 206.59791390000001,
                            StartId = new Guid("f92a5462-0f86-427c-af3d-9a060541e10f"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("5a1a8ceb-034d-4cf6-96b3-1608b9835ec5"),
                            FinishId = new Guid("908e6cd9-721f-4059-8524-1446f20fa76e"),
                            Length = 456.26762389999999,
                            StartId = new Guid("212bd650-8044-4eac-a7f0-2de2e5418055"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("3a44daf9-6571-40e5-94d7-0281682ce950"),
                            FinishId = new Guid("dd11d2b1-4aad-4bbc-8d2c-ee1fdf7016d5"),
                            Length = 145.18263640000001,
                            StartId = new Guid("ea00f8af-6563-47a5-b18c-cfa158992574"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("d239c0d4-c8e2-435b-9122-9f9813663061"),
                            FinishId = new Guid("ad1b7ade-f60d-42de-bd26-245b5c2896bf"),
                            Length = 275.66045489999999,
                            StartId = new Guid("82a602e8-3292-4abd-b789-49881648560e"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("f06d0a1b-5a76-4477-a82f-a77598eb6f9e"),
                            FinishId = new Guid("4936ca2d-e5cc-4e90-ab86-783d26d1d0d4"),
                            Length = 130.30811159999999,
                            StartId = new Guid("99eee87a-44f0-4c58-8280-b2841a7877ca"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("a745ddb9-fd7e-48a0-b24d-6f5c9a25a6fa"),
                            FinishId = new Guid("677ba9cb-b788-43db-b112-424a97897b68"),
                            Length = 58.957502009999999,
                            StartId = new Guid("bb91bbf3-a7f9-4a42-9f28-d243e2ad2385"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("680b5fd8-50bb-496d-942f-acfe6924e42c"),
                            FinishId = new Guid("773dc3d2-e99d-4961-bacc-e48ee2077e97"),
                            Length = 280.78065989999999,
                            StartId = new Guid("a5be7d44-5aae-45e2-9b49-c4feae163087"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("18287269-fd12-4fa9-a585-0914c3f3e4a9"),
                            FinishId = new Guid("db51c0e2-be6a-44f5-9c7f-95c44b0a044e"),
                            Length = 227.22693039999999,
                            StartId = new Guid("212bd650-8044-4eac-a7f0-2de2e5418055"),
                            StatusRoute = 1
                        },
                        new
                        {
                            Id = new Guid("29163ac9-5508-4788-90f9-df581dbcdc4b"),
                            FinishId = new Guid("0b1181cd-caed-4b02-9f5b-f28f9a6f5024"),
                            Length = 124.90922089999999,
                            StartId = new Guid("1dc4ae04-bed8-43e8-b2a0-edecdccc8604"),
                            StatusRoute = 2
                        },
                        new
                        {
                            Id = new Guid("6d363b07-d8d5-40a9-9bc3-6f8765c27a71"),
                            FinishId = new Guid("ad1b7ade-f60d-42de-bd26-245b5c2896bf"),
                            Length = 285.07951350000002,
                            StartId = new Guid("89e8c2a2-20a6-4d42-8e54-4b06557149ba"),
                            StatusRoute = 2
                        });
                });

            modelBuilder.Entity("backend.Models.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ShipClassId");

                    b.ToTable("Ship");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ea595de-d569-4080-afd3-3aad34244ca0"),
                            ShipClassId = new Guid("24a28048-93d7-4a95-8f78-6eb02e49997f"),
                            ShipName = "ДЮК II",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("f6f8654f-ba37-4042-aded-56494ffa8a9c"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "САРМАТ",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("f5d79e86-4e94-4034-9a6b-5c196815c479"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "EDUARD TOLL",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("bf709fb0-9ab5-44a3-af45-397158e73fff"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "GEORGIY USHAKOV",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("afdc1143-a0cd-47fe-affe-7faf91545e36"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "RUDOLF SAMOYLOVICH",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("0ce92a05-a001-4f05-aa56-55c26a2ae264"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "VLADIMIR VORONIN",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("bff00bda-008b-4b52-ac59-caef3ac70531"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "NIKOLAY YEVGENOV",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("731e5d45-02e4-463d-ae77-557ed26bc626"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "CHRISTOPHE DE MARGERIE",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("e58e5577-f2ca-437d-acff-a194402618d5"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "BORIS VILKITSKY",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = new Guid("620df577-d79d-4287-a580-1e10f8b400d8"),
                            ShipClassId = new Guid("24a28048-93d7-4a95-8f78-6eb02e49997f"),
                            ShipName = "АРКТИКА-2",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = new Guid("89c6d2da-c522-4045-94f6-6003abd7dc30"),
                            ShipClassId = new Guid("24a28048-93d7-4a95-8f78-6eb02e49997f"),
                            ShipName = "ИНЖЕНЕР ВЕШНЯКОВ",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = new Guid("e0837184-26a5-4e8c-8495-4f691f43393e"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "ТАМБЕЙ",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = new Guid("fdbf48b1-bc05-4cfe-8719-0fd056a6caf1"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "ШТУРМАН АЛЬБАНОВ",
                            Speed = 19.0
                        },
                        new
                        {
                            Id = new Guid("13006a34-afa7-419b-ab2d-9ad5bf58f10b"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "НИКИФОР БЕГИЧЕВ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("3ea882af-e532-4a4d-aac6-f245f8c18189"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "НОРИЛЬСКИЙ НИКЕЛЬ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("166b610d-b26d-44ce-8a50-6aa65943a152"),
                            ShipClassId = new Guid("24a28048-93d7-4a95-8f78-6eb02e49997f"),
                            ShipName = "АЙС ИГЛ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("8d8e16e9-fa36-4485-b158-a83dc4aaa4fc"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "ШТУРМАН КОШЕЛЕВ",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("a79ce3ea-331a-4d26-8ae0-6afbcf99fdb5"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "ШТУРМАН ЩЕРБИНИН",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("9fb340d6-60ff-4beb-981f-cf823e000af5"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "ШТУРМАН СКУРАТОВ",
                            Speed = 15.0
                        },
                        new
                        {
                            Id = new Guid("75eda394-bdac-43ae-8aab-401871f6cbf1"),
                            ShipClassId = new Guid("24a28048-93d7-4a95-8f78-6eb02e49997f"),
                            ShipName = "ИОГАНН МАХМАСТАЛЬ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("ee4abf71-c451-496a-9673-ba67372d85c2"),
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipName = "BORIS SOKOLOV",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("e9ab1c2c-2d5a-4f35-adc9-aeb242a3a866"),
                            ShipClassId = new Guid("24a28048-93d7-4a95-8f78-6eb02e49997f"),
                            ShipName = "ИНЖЕНЕР ТРУБИН",
                            Speed = 12.0
                        },
                        new
                        {
                            Id = new Guid("cd9fa120-1598-4c66-bc8a-7aabdd3dba40"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "БАРЕНЦ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("e4fa97a0-a870-4c33-9365-a2ad6692fa70"),
                            ShipClassId = new Guid("24a28048-93d7-4a95-8f78-6eb02e49997f"),
                            ShipName = "ПОЛАР КИНГ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("27e8de50-155b-4bbe-ab9e-4ab97924f5c9"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "МЫС ДЕЖНЕВА",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("b655f2a9-1333-4328-98b0-8b5af70060e7"),
                            ShipClassId = new Guid("24a28048-93d7-4a95-8f78-6eb02e49997f"),
                            ShipName = "СЕВМОРПУТЬ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("a9ed7947-7ee4-4ca9-a5a5-0f1dcae3c47c"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "ГРИГОРИЙ ШЕЛИХОВ",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("c5fb5436-9f3a-4e0b-8d42-01afeb4228df"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "УРАРТУ",
                            Speed = 18.0
                        },
                        new
                        {
                            Id = new Guid("cfae4da7-db79-439e-8d3e-7123b3382779"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "ФЕСКО ПАРИС",
                            Speed = 18.0
                        },
                        new
                        {
                            Id = new Guid("68f2a992-7440-4216-a0e2-fc276dde9d2e"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "ПРОГРЕСС",
                            Speed = 18.0
                        },
                        new
                        {
                            Id = new Guid("545f2486-5880-41c7-9f20-9d7ee9d5f853"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "МИХАИЛ БРИТНЕВ",
                            Speed = 18.0
                        },
                        new
                        {
                            Id = new Guid("3f29bf7f-cd55-4abd-b95b-7034db6f32c8"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "САБЕТТА",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("205389a0-50b0-4ff4-9a60-698394c60e09"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "ГЕОРГИЙ УШАКОВ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("9330ddaa-4ce1-40aa-8507-524495b22983"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "СЕВЕРНЫЙ ПРОЕКТ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("fc571784-71c0-4585-a6f9-11d32e2e2b05"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "БЕРИНГ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("f4cfbbde-b74c-40e6-bede-e9a0b9f75d30"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "ТОЛБУХИН",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("5fb56d6b-b856-49fc-947e-e922eadc2740"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "ЯМАЛ КРЕЧЕТ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("52c7d1b5-86fd-4eba-948b-cef0e9a2c0a4"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "CLEAN VISION",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("062ef17f-7598-4834-88ea-41cc577a4308"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "ТИКСИ",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("f506055e-85a7-4af5-9514-823e6e6fbfa5"),
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipName = "ТАЙБОЛА",
                            Speed = 16.0
                        },
                        new
                        {
                            Id = new Guid("d50dc226-41a2-4410-90a8-109e6b8d70a7"),
                            ShipClassId = new Guid("8ddd4672-e038-4ad7-bcb4-674a5a6f578f"),
                            ShipName = "YAMAL SPIRIT",
                            Speed = 14.0
                        },
                        new
                        {
                            Id = new Guid("6a14d71e-c638-428e-80d6-d7e246d6904b"),
                            ShipClassId = new Guid("8ddd4672-e038-4ad7-bcb4-674a5a6f578f"),
                            ShipName = "НИКОЛАЙ ЧУДОТВОРЕЦ",
                            Speed = 16.0
                        });
                });

            modelBuilder.Entity("backend.Models.ShipClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ShipType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShipClass");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ddd4672-e038-4ad7-bcb4-674a5a6f578f"),
                            ShipType = "Without class"
                        },
                        new
                        {
                            Id = new Guid("38a774ab-0b3f-4c1f-85ee-843a5f79b761"),
                            ShipType = "Ice1"
                        },
                        new
                        {
                            Id = new Guid("c1215be6-e04c-4933-9187-3f51255934b8"),
                            ShipType = "Ice2"
                        },
                        new
                        {
                            Id = new Guid("aaffa9d4-beb6-403b-8d40-e9330d52d6ad"),
                            ShipType = "Ice3"
                        },
                        new
                        {
                            Id = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4"),
                            ShipType = "Arc4"
                        },
                        new
                        {
                            Id = new Guid("24a28048-93d7-4a95-8f78-6eb02e49997f"),
                            ShipType = "Arc5"
                        },
                        new
                        {
                            Id = new Guid("c936f471-3544-481c-a7eb-0d5fa15fea2f"),
                            ShipType = "Arc6"
                        },
                        new
                        {
                            Id = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d"),
                            ShipType = "Arc7"
                        },
                        new
                        {
                            Id = new Guid("6c5ae688-e271-425e-862f-16aaad546c67"),
                            ShipType = "Arc9-1"
                        },
                        new
                        {
                            Id = new Guid("5aee99a9-954a-4b73-9064-d94eb49a582d"),
                            ShipType = "Arc9-2"
                        });
                });

            modelBuilder.Entity("backend.Models.ShipClassIntegerClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Debuff")
                        .HasColumnType("boolean");

                    b.Property<double?>("DebuffHelpValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("DebuffValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("IntegerIceClassId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCanHelpMove")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCanSoloMove")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ShipClassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IntegerIceClassId");

                    b.HasIndex("ShipClassId");

                    b.ToTable("ShipClassIntegerClass");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41c0e89c-dd10-4e8d-aeab-708bafc14826"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("273502cb-25c1-4811-aa80-7f6fa487daed"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("8ddd4672-e038-4ad7-bcb4-674a5a6f578f")
                        },
                        new
                        {
                            Id = new Guid("0720d540-663c-4160-ac82-5787862e3ea9"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("2c6b5909-cab9-43c0-9035-20513bcfa901"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("8ddd4672-e038-4ad7-bcb4-674a5a6f578f")
                        },
                        new
                        {
                            Id = new Guid("085cd09f-0460-4e36-bc6e-4b7cacce5e2d"),
                            Debuff = false,
                            DebuffHelpValue = 0.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("96e66895-a43d-4e62-9ae4-c1c7e939b125"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("8ddd4672-e038-4ad7-bcb4-674a5a6f578f")
                        },
                        new
                        {
                            Id = new Guid("ba0da3bf-cc87-41e4-8839-76c998230a47"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("273502cb-25c1-4811-aa80-7f6fa487daed"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("38a774ab-0b3f-4c1f-85ee-843a5f79b761")
                        },
                        new
                        {
                            Id = new Guid("a6e883d4-1d5e-4d11-9c92-13724a421171"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("2c6b5909-cab9-43c0-9035-20513bcfa901"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("38a774ab-0b3f-4c1f-85ee-843a5f79b761")
                        },
                        new
                        {
                            Id = new Guid("4f052eb1-1fd0-4c69-9284-cda57eddd96b"),
                            Debuff = false,
                            DebuffHelpValue = 0.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("96e66895-a43d-4e62-9ae4-c1c7e939b125"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("38a774ab-0b3f-4c1f-85ee-843a5f79b761")
                        },
                        new
                        {
                            Id = new Guid("d3ced798-f4b0-496d-b2a0-e3a39aca9af7"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("273502cb-25c1-4811-aa80-7f6fa487daed"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("c1215be6-e04c-4933-9187-3f51255934b8")
                        },
                        new
                        {
                            Id = new Guid("4d6b3f6a-6738-4683-b872-d97ca0c40e4a"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("2c6b5909-cab9-43c0-9035-20513bcfa901"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("c1215be6-e04c-4933-9187-3f51255934b8")
                        },
                        new
                        {
                            Id = new Guid("e8522892-e79a-40e4-bb14-a1c13f7dcdae"),
                            Debuff = false,
                            DebuffHelpValue = 0.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("96e66895-a43d-4e62-9ae4-c1c7e939b125"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("c1215be6-e04c-4933-9187-3f51255934b8")
                        },
                        new
                        {
                            Id = new Guid("8b7a4986-326d-4ce2-be7c-f38e9417947c"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("273502cb-25c1-4811-aa80-7f6fa487daed"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("aaffa9d4-beb6-403b-8d40-e9330d52d6ad")
                        },
                        new
                        {
                            Id = new Guid("ce97b638-e426-425d-9b1d-e05b5d37a067"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("2c6b5909-cab9-43c0-9035-20513bcfa901"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("aaffa9d4-beb6-403b-8d40-e9330d52d6ad")
                        },
                        new
                        {
                            Id = new Guid("bae08958-f7ef-4981-9439-f122e230283c"),
                            Debuff = false,
                            DebuffHelpValue = 0.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("96e66895-a43d-4e62-9ae4-c1c7e939b125"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("aaffa9d4-beb6-403b-8d40-e9330d52d6ad")
                        },
                        new
                        {
                            Id = new Guid("7c18a9ee-bb52-48eb-96e1-da328fc7e5b0"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("273502cb-25c1-4811-aa80-7f6fa487daed"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4")
                        },
                        new
                        {
                            Id = new Guid("3c63f759-e688-4364-9eb8-396bad010c48"),
                            Debuff = true,
                            DebuffHelpValue = 0.80000000000000004,
                            DebuffValue = 0.80000000000000004,
                            IntegerIceClassId = new Guid("2c6b5909-cab9-43c0-9035-20513bcfa901"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4")
                        },
                        new
                        {
                            Id = new Guid("cf756440-67b6-4ca2-914a-21fcb4304d0a"),
                            Debuff = true,
                            DebuffHelpValue = 0.80000000000000004,
                            DebuffValue = 0.69999999999999996,
                            IntegerIceClassId = new Guid("96e66895-a43d-4e62-9ae4-c1c7e939b125"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("fe915ee7-abf6-4dfc-a18e-ab43905956f4")
                        },
                        new
                        {
                            Id = new Guid("85fd6972-e7fe-48a1-b992-aea79fa0ba75"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("273502cb-25c1-4811-aa80-7f6fa487daed"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("24a28048-93d7-4a95-8f78-6eb02e49997f")
                        },
                        new
                        {
                            Id = new Guid("296afdff-cdf6-4103-bff6-e8e736e802c3"),
                            Debuff = true,
                            DebuffHelpValue = 0.80000000000000004,
                            DebuffValue = 0.80000000000000004,
                            IntegerIceClassId = new Guid("2c6b5909-cab9-43c0-9035-20513bcfa901"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("24a28048-93d7-4a95-8f78-6eb02e49997f")
                        },
                        new
                        {
                            Id = new Guid("ec57acee-a085-4cc6-b96a-f1de6ccfea9f"),
                            Debuff = true,
                            DebuffHelpValue = 0.80000000000000004,
                            DebuffValue = 0.69999999999999996,
                            IntegerIceClassId = new Guid("96e66895-a43d-4e62-9ae4-c1c7e939b125"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("24a28048-93d7-4a95-8f78-6eb02e49997f")
                        },
                        new
                        {
                            Id = new Guid("03ece519-9483-44ab-a348-942fc7b246de"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("273502cb-25c1-4811-aa80-7f6fa487daed"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("c936f471-3544-481c-a7eb-0d5fa15fea2f")
                        },
                        new
                        {
                            Id = new Guid("25f059eb-0f19-4ba0-8277-68aea1cb9599"),
                            Debuff = true,
                            DebuffHelpValue = 0.80000000000000004,
                            DebuffValue = 0.80000000000000004,
                            IntegerIceClassId = new Guid("2c6b5909-cab9-43c0-9035-20513bcfa901"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("c936f471-3544-481c-a7eb-0d5fa15fea2f")
                        },
                        new
                        {
                            Id = new Guid("fa34d8b2-be0b-4df8-8184-a18edf407a9e"),
                            Debuff = true,
                            DebuffHelpValue = 0.80000000000000004,
                            DebuffValue = 0.69999999999999996,
                            IntegerIceClassId = new Guid("96e66895-a43d-4e62-9ae4-c1c7e939b125"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("c936f471-3544-481c-a7eb-0d5fa15fea2f")
                        },
                        new
                        {
                            Id = new Guid("14ea59ab-3b9c-44b8-b9f1-8214d093a768"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("273502cb-25c1-4811-aa80-7f6fa487daed"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d")
                        },
                        new
                        {
                            Id = new Guid("846e4ce7-b732-485c-a9a7-c34d200cac85"),
                            Debuff = true,
                            DebuffHelpValue = 0.80000000000000004,
                            DebuffValue = 0.59999999999999998,
                            IntegerIceClassId = new Guid("2c6b5909-cab9-43c0-9035-20513bcfa901"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d")
                        },
                        new
                        {
                            Id = new Guid("c5932f6f-bacc-43ef-99e0-69ecbbbca642"),
                            Debuff = true,
                            DebuffHelpValue = 0.80000000000000004,
                            DebuffValue = 0.14999999999999999,
                            IntegerIceClassId = new Guid("96e66895-a43d-4e62-9ae4-c1c7e939b125"),
                            IsCanHelpMove = true,
                            IsCanSoloMove = false,
                            ShipClassId = new Guid("52258aa1-4296-4067-b1db-bdb1abfdd51d")
                        },
                        new
                        {
                            Id = new Guid("e082f491-0ae6-4447-8d35-4faf7b76ff2f"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("273502cb-25c1-4811-aa80-7f6fa487daed"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("6c5ae688-e271-425e-862f-16aaad546c67")
                        },
                        new
                        {
                            Id = new Guid("3446e13a-2fca-4171-8d2c-8284f7fa7d1f"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("2c6b5909-cab9-43c0-9035-20513bcfa901"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("6c5ae688-e271-425e-862f-16aaad546c67")
                        },
                        new
                        {
                            Id = new Guid("fe554c64-bd2a-4999-a6f6-90c33de6bf35"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("96e66895-a43d-4e62-9ae4-c1c7e939b125"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("6c5ae688-e271-425e-862f-16aaad546c67")
                        },
                        new
                        {
                            Id = new Guid("ac36fb3a-ceef-4c57-a00a-3ee2af693a10"),
                            Debuff = false,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 1.0,
                            IntegerIceClassId = new Guid("273502cb-25c1-4811-aa80-7f6fa487daed"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("5aee99a9-954a-4b73-9064-d94eb49a582d")
                        },
                        new
                        {
                            Id = new Guid("728c8d56-c782-4fe4-82a4-65773594145a"),
                            Debuff = true,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 0.90000000000000002,
                            IntegerIceClassId = new Guid("2c6b5909-cab9-43c0-9035-20513bcfa901"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("5aee99a9-954a-4b73-9064-d94eb49a582d")
                        },
                        new
                        {
                            Id = new Guid("e5887bae-5406-42f7-9a7f-fe1b056d61c2"),
                            Debuff = true,
                            DebuffHelpValue = 1.0,
                            DebuffValue = 0.75,
                            IntegerIceClassId = new Guid("96e66895-a43d-4e62-9ae4-c1c7e939b125"),
                            IsCanHelpMove = false,
                            IsCanSoloMove = true,
                            ShipClassId = new Guid("5aee99a9-954a-4b73-9064-d94eb49a582d")
                        });
                });

            modelBuilder.Entity("backend.Models.Route", b =>
                {
                    b.HasOne("backend.Models.GraphData", "Finish")
                        .WithMany()
                        .HasForeignKey("FinishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.GraphData", "Start")
                        .WithMany()
                        .HasForeignKey("StartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finish");

                    b.Navigation("Start");
                });

            modelBuilder.Entity("backend.Models.Ship", b =>
                {
                    b.HasOne("backend.Models.ShipClass", "ShipClass")
                        .WithMany("Ship")
                        .HasForeignKey("ShipClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipClass");
                });

            modelBuilder.Entity("backend.Models.ShipClassIntegerClass", b =>
                {
                    b.HasOne("backend.Models.IntegerIceClass", "IntegerIceClass")
                        .WithMany("ShipClassIntegerClasses")
                        .HasForeignKey("IntegerIceClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ShipClass", "ShipClass")
                        .WithMany("ShipClassIntegerClasses")
                        .HasForeignKey("ShipClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegerIceClass");

                    b.Navigation("ShipClass");
                });

            modelBuilder.Entity("backend.Models.IntegerIceClass", b =>
                {
                    b.Navigation("ShipClassIntegerClasses");
                });

            modelBuilder.Entity("backend.Models.ShipClass", b =>
                {
                    b.Navigation("Ship");

                    b.Navigation("ShipClassIntegerClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
