name: Deploy buy runner

on:
  push:
    branches: [ "main" ]
jobs:
   prepare-environment:
    defaults:
      run:
        working-directory: ./backend/backend
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Clean
      run: dotnet clean --configuration Release --os linux 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --property:Configuration=Release --os linux 
   deploy:
    runs-on: self-hosted
    needs: prepare-environment
    defaults:
      run:
        working-directory: ./backend/backend
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: run
        run: dotnet run --property:Configuration=Release --os linux 
