name: Deploy buy runner

on:
  push:
    branches: [ "main" ]
jobs:
   prepare-environment:
    defaults:
      run:
        working-directory: ./backend/backend
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Clean
      run: dotnet clean --configuration Release 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --property:Configuration=Release --os linux 
